#!/bin/sh
# ═══════════════════════════════════════════════════════════════════════════════
# PgBouncer Entrypoint Script for SAHOOL Platform
# Generates userlist.txt from environment variables before starting PgBouncer
#
# This script:
# 1. Waits for PostgreSQL to be ready (using netcat/nc)
# 2. Generates userlist.txt with auth_user credentials
# 3. Starts PgBouncer with the generated configuration
#
# Compatible with Alpine-based images (edoburu/pgbouncer)
# ═══════════════════════════════════════════════════════════════════════════════

set -e

# Create runtime directory with proper permissions
# Note: edoburu/pgbouncer (Alpine-based) may run as 'postgres' user or other
mkdir -p /etc/pgbouncer/runtime

# Only change ownership if pgbouncer user exists in the container
if id pgbouncer >/dev/null 2>&1; then
    chown -R pgbouncer:pgbouncer /etc/pgbouncer/runtime 2>/dev/null || true
fi

# chmod may fail due to security settings (no-new-privileges) - make it non-fatal
chmod 700 /etc/pgbouncer/runtime 2>/dev/null || true

# Configuration from environment
DB_HOST="${DB_HOST:-postgres}"
DB_PORT="${DB_PORT:-5432}"
DB_USER="${DB_USER:-sahool}"
DB_PASSWORD="${DB_PASSWORD:-}"
DB_NAME="${DB_NAME:-sahool}"
PGBOUNCER_CONFIG="${PGBOUNCER_CONFIG:-/etc/pgbouncer/pgbouncer.ini}"
USERLIST_FILE="${USERLIST_FILE:-/etc/pgbouncer/runtime/userlist.txt}"

# Logging functions
log_info() {
    echo "[INFO] $(date '+%Y-%m-%d %H:%M:%S') $1"
}

log_warn() {
    echo "[WARN] $(date '+%Y-%m-%d %H:%M:%S') $1"
}

log_error() {
    echo "[ERROR] $(date '+%Y-%m-%d %H:%M:%S') $1"
}

# ═══════════════════════════════════════════════════════════════════════════════
# Wait for PostgreSQL to be ready using netcat (available in Alpine)
# ═══════════════════════════════════════════════════════════════════════════════
wait_for_postgres() {
    _max_attempts=30
    _attempt=1

    log_info "Waiting for PostgreSQL at ${DB_HOST}:${DB_PORT}..."

    while [ "$_attempt" -le "$_max_attempts" ]; do
        # Try to connect to PostgreSQL port using nc (netcat)
        if nc -z "$DB_HOST" "$DB_PORT" 2>/dev/null; then
            log_info "PostgreSQL port is open!"
            # Give PostgreSQL a moment to finish initialization
            sleep 2
            return 0
        fi

        log_warn "Attempt $_attempt/$_max_attempts: PostgreSQL not ready, waiting..."
        sleep 2
        _attempt=$((_attempt + 1))
    done

    log_error "PostgreSQL did not become ready in time"
    return 1
}

# ═══════════════════════════════════════════════════════════════════════════════
# Generate userlist.txt with plaintext password
# PgBouncer will use this to authenticate as auth_user to PostgreSQL
# ═══════════════════════════════════════════════════════════════════════════════
generate_userlist() {
    log_info "Generating userlist.txt for auth_user: ${DB_USER}"

    if [ -z "$DB_PASSWORD" ]; then
        log_error "DB_PASSWORD is not set. Cannot generate userlist.txt"
        return 1
    fi

    # Create userlist.txt directory if it doesn't exist
    mkdir -p "$(dirname "$USERLIST_FILE")"

    # Write userlist.txt with plaintext passwords
    # PgBouncer accepts plaintext passwords in the userlist file
    # Format: "username" "password"
    cat > "$USERLIST_FILE" << EOF
;; PgBouncer User List - Auto-generated by entrypoint.sh
;; Generated: $(date '+%Y-%m-%d %H:%M:%S')
;; DO NOT EDIT MANUALLY - This file is regenerated on container start
;;
;; Format: "username" "password"
;; PgBouncer uses these credentials to authenticate to PostgreSQL via auth_query

"${DB_USER}" "${DB_PASSWORD}"

;; Admin users for PgBouncer admin console (same password for simplicity)
"pgbouncer_admin" "${PGBOUNCER_ADMIN_PASSWORD:-${DB_PASSWORD}}"
"pgbouncer_stats" "${PGBOUNCER_STATS_PASSWORD:-${DB_PASSWORD}}"
EOF

    # Set proper permissions (readable by pgbouncer process)
    # chmod may fail due to security settings - make it non-fatal
    chmod 600 "$USERLIST_FILE" 2>/dev/null || true

    log_info "userlist.txt generated successfully at ${USERLIST_FILE}"
}

# ═══════════════════════════════════════════════════════════════════════════════
# Verify PgBouncer configuration
# ═══════════════════════════════════════════════════════════════════════════════
verify_config() {
    log_info "Verifying PgBouncer configuration..."

    # Ensure the config file exists
    if [ ! -f "$PGBOUNCER_CONFIG" ]; then
        log_error "PgBouncer config file not found: $PGBOUNCER_CONFIG"
        return 1
    fi

    # Ensure userlist file exists
    if [ ! -f "$USERLIST_FILE" ]; then
        log_error "Userlist file not found: $USERLIST_FILE"
        return 1
    fi

    log_info "PgBouncer configuration verified"
    log_info "  Config: ${PGBOUNCER_CONFIG}"
    log_info "  Userlist: ${USERLIST_FILE}"
}

# ═══════════════════════════════════════════════════════════════════════════════
# Main execution
# ═══════════════════════════════════════════════════════════════════════════════
main() {
    log_info "═══════════════════════════════════════════════════════════════════"
    log_info "SAHOOL PgBouncer Entrypoint v2.0"
    log_info "═══════════════════════════════════════════════════════════════════"
    log_info "DB_HOST: ${DB_HOST}"
    log_info "DB_PORT: ${DB_PORT}"
    log_info "DB_USER: ${DB_USER}"
    log_info "DB_NAME: ${DB_NAME}"
    log_info "═══════════════════════════════════════════════════════════════════"

    # Wait for PostgreSQL
    if ! wait_for_postgres; then
        log_warn "PostgreSQL not available, but continuing anyway..."
    fi

    # Generate userlist.txt
    if ! generate_userlist; then
        log_error "Failed to generate userlist.txt"
        exit 1
    fi

    # Verify config
    if ! verify_config; then
        log_error "Configuration verification failed"
        exit 1
    fi

    log_info "Starting PgBouncer..."
    log_info "═══════════════════════════════════════════════════════════════════"

    # Execute pgbouncer with the config file
    # Use exec to replace the shell process with pgbouncer
    exec pgbouncer "$PGBOUNCER_CONFIG"
}

main "$@"
