# ============================================================================
# Resource Quotas and Limit Ranges for Cost Optimization
# حصص الموارد ونطاقات الحدود لتحسين التكاليف
# ============================================================================

# Production Namespace Quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: sahool-production-quota
  namespace: sahool
  labels:
    app.kubernetes.io/part-of: sahool-cost-optimization
spec:
  hard:
    # Compute resources
    requests.cpu: "50"
    requests.memory: 100Gi
    limits.cpu: "100"
    limits.memory: 200Gi

    # Storage
    requests.storage: 500Gi
    persistentvolumeclaims: "50"

    # Objects count
    pods: "200"
    services: "50"
    secrets: "100"
    configmaps: "100"
    replicationcontrollers: "50"

    # Services
    services.loadbalancers: "5"
    services.nodeports: "10"
---
# Staging Namespace Quota (Lower limits)
apiVersion: v1
kind: ResourceQuota
metadata:
  name: sahool-staging-quota
  namespace: sahool-staging
  labels:
    app.kubernetes.io/part-of: sahool-cost-optimization
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    requests.storage: 100Gi
    persistentvolumeclaims: "20"
    pods: "100"
    services: "30"
    services.loadbalancers: "2"
---
# Limit Range for Production
apiVersion: v1
kind: LimitRange
metadata:
  name: sahool-production-limits
  namespace: sahool
  labels:
    app.kubernetes.io/part-of: sahool-cost-optimization
spec:
  limits:
    # Default limits for containers
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      max:
        cpu: 4
        memory: 8Gi
      min:
        cpu: 50m
        memory: 64Mi

    # Pod limits
    - type: Pod
      max:
        cpu: 8
        memory: 16Gi

    # PVC limits
    - type: PersistentVolumeClaim
      max:
        storage: 100Gi
      min:
        storage: 1Gi
---
# Limit Range for Staging
apiVersion: v1
kind: LimitRange
metadata:
  name: sahool-staging-limits
  namespace: sahool-staging
  labels:
    app.kubernetes.io/part-of: sahool-cost-optimization
spec:
  limits:
    - type: Container
      default:
        cpu: 200m
        memory: 256Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: 2
        memory: 4Gi
      min:
        cpu: 25m
        memory: 32Mi
---
# Priority Class for Cost-Sensitive Workloads
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: sahool-low-priority
  labels:
    app.kubernetes.io/part-of: sahool-cost-optimization
value: 100
globalDefault: false
description: "Low priority for non-critical workloads that can be preempted"
preemptionPolicy: PreemptLowerPriority
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: sahool-high-priority
  labels:
    app.kubernetes.io/part-of: sahool-cost-optimization
value: 1000
globalDefault: false
description: "High priority for critical production workloads"
preemptionPolicy: PreemptLowerPriority
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: sahool-default
  labels:
    app.kubernetes.io/part-of: sahool-cost-optimization
value: 500
globalDefault: true
description: "Default priority for standard workloads"
preemptionPolicy: PreemptLowerPriority
