"""
Planner Agent
=============
وكيل التخطيط

Read-only planning agent inspired by OpenCode's Plan mode.
Creates execution plans without making changes.

Features:
- Safe exploration of codebase/data
- Creates detailed execution plans
- Requests approval before execution
- No write operations

Author: SAHOOL Platform Team
Updated: January 2026
"""

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

import structlog

from .base import (
    AgentMode,
    AgentStep,
    AgentTool,
    BaseAutonomousAgent,
    ToolResult,
)
from ..llm_provider import LLMProviderManager

logger = structlog.get_logger()


@dataclass
class ExecutionPlan:
    """
    Execution plan generated by the planner.
    خطة التنفيذ المولدة من المخطط
    """
    plan_id: str
    title: str
    title_ar: str
    description: str
    description_ar: str
    steps: list[dict[str, Any]] = field(default_factory=list)
    estimated_duration_minutes: int = 0
    risk_level: str = "low"  # low, medium, high
    requires_approval: bool = True
    resources_needed: list[str] = field(default_factory=list)
    created_at: datetime = field(default_factory=datetime.utcnow)

    def to_dict(self) -> dict[str, Any]:
        return {
            "plan_id": self.plan_id,
            "title": self.title,
            "title_ar": self.title_ar,
            "description": self.description,
            "description_ar": self.description_ar,
            "steps": self.steps,
            "estimated_duration_minutes": self.estimated_duration_minutes,
            "risk_level": self.risk_level,
            "requires_approval": self.requires_approval,
            "resources_needed": self.resources_needed,
            "created_at": self.created_at.isoformat(),
        }


class PlannerAgent(BaseAutonomousAgent):
    """
    Read-only Planner Agent.
    وكيل التخطيط للقراءة فقط

    Inspired by OpenCode's Plan agent:
    - Analyzes requests without making changes
    - Creates detailed execution plans
    - Identifies risks and requirements
    - Returns plan for approval

    Use cases:
    - Seasonal planning for farms
    - Crop rotation planning
    - Resource allocation
    - Risk assessment

    Example:
        planner = PlannerAgent()

        plan = await planner.create_plan(
            objective="Plan wheat planting for Field F003",
            context={"field_id": "F003", "season": "winter"}
        )

        print(plan.steps)  # View the plan
        # User can then approve and execute with FarmAdvisorAgent
    """

    def __init__(
        self,
        tenant_id: str = "sahool",
        llm_manager: LLMProviderManager | None = None,
    ):
        super().__init__(
            agent_id="planner-agent",
            name="Planner Agent",
            name_ar="وكيل التخطيط",
            description="Read-only planning agent for agricultural operations",
            description_ar="وكيل تخطيط للقراءة فقط للعمليات الزراعية",
            mode=AgentMode.PLAN,  # Always PLAN mode
            tenant_id=tenant_id,
            llm_manager=llm_manager,
        )

        self.current_plan: ExecutionPlan | None = None

    def _register_default_tools(self) -> None:
        """Register read-only planning tools."""

        # Tool 1: Analyze Field History
        self.register_tool(AgentTool(
            name="analyze_field_history",
            name_ar="تحليل تاريخ الحقل",
            description="Analyze historical data for a field (crops, yields, issues)",
            description_ar="تحليل البيانات التاريخية للحقل (المحاصيل، الإنتاج، المشاكل)",
            input_schema={
                "type": "object",
                "properties": {
                    "field_id": {"type": "string"},
                    "years": {"type": "integer", "default": 3},
                },
                "required": ["field_id"]
            },
            handler=self._analyze_field_history,
            tags=["analysis", "history"],
        ))

        # Tool 2: Check Resource Availability
        self.register_tool(AgentTool(
            name="check_resources",
            name_ar="فحص الموارد",
            description="Check availability of resources (water, equipment, labor)",
            description_ar="فحص توفر الموارد (المياه، المعدات، العمالة)",
            input_schema={
                "type": "object",
                "properties": {
                    "farm_id": {"type": "string"},
                    "resource_types": {
                        "type": "array",
                        "items": {"type": "string"},
                        "default": ["water", "equipment", "labor"]
                    },
                    "date_range": {"type": "object"},
                },
                "required": ["farm_id"]
            },
            handler=self._check_resources,
            tags=["resources", "availability"],
        ))

        # Tool 3: Assess Weather Window
        self.register_tool(AgentTool(
            name="assess_weather_window",
            name_ar="تقييم نافذة الطقس",
            description="Assess optimal weather windows for operations",
            description_ar="تقييم النوافذ الجوية المثلى للعمليات",
            input_schema={
                "type": "object",
                "properties": {
                    "location": {"type": "object"},
                    "operation_type": {
                        "type": "string",
                        "enum": ["planting", "irrigation", "spraying", "harvest"]
                    },
                    "days_ahead": {"type": "integer", "default": 14},
                },
                "required": ["operation_type"]
            },
            handler=self._assess_weather_window,
            tags=["weather", "timing"],
        ))

        # Tool 4: Evaluate Crop Rotation Options
        self.register_tool(AgentTool(
            name="evaluate_rotation",
            name_ar="تقييم التناوب المحصولي",
            description="Evaluate crop rotation options for a field",
            description_ar="تقييم خيارات التناوب المحصولي للحقل",
            input_schema={
                "type": "object",
                "properties": {
                    "field_id": {"type": "string"},
                    "current_crop": {"type": "string"},
                    "season": {"type": "string"},
                    "constraints": {"type": "object"},
                },
                "required": ["field_id"]
            },
            handler=self._evaluate_rotation,
            tags=["rotation", "planning"],
        ))

        # Tool 5: Calculate Costs
        self.register_tool(AgentTool(
            name="calculate_costs",
            name_ar="حساب التكاليف",
            description="Calculate estimated costs for an operation",
            description_ar="حساب التكاليف المقدرة لعملية",
            input_schema={
                "type": "object",
                "properties": {
                    "operation_type": {"type": "string"},
                    "field_id": {"type": "string"},
                    "area_ha": {"type": "number"},
                    "inputs": {"type": "array", "items": {"type": "object"}},
                },
                "required": ["operation_type"]
            },
            handler=self._calculate_costs,
            tags=["costs", "budget"],
        ))

        # Tool 6: Assess Risks
        self.register_tool(AgentTool(
            name="assess_risks",
            name_ar="تقييم المخاطر",
            description="Assess risks for a planned operation",
            description_ar="تقييم المخاطر لعملية مخطط لها",
            input_schema={
                "type": "object",
                "properties": {
                    "operation": {"type": "object"},
                    "field_id": {"type": "string"},
                    "timing": {"type": "string"},
                },
                "required": ["operation"]
            },
            handler=self._assess_risks,
            tags=["risk", "assessment"],
        ))

        # Tool 7: Generate Plan Document
        self.register_tool(AgentTool(
            name="generate_plan_document",
            name_ar="توليد وثيقة الخطة",
            description="Generate a formal execution plan document",
            description_ar="توليد وثيقة خطة تنفيذ رسمية",
            input_schema={
                "type": "object",
                "properties": {
                    "title": {"type": "string"},
                    "title_ar": {"type": "string"},
                    "steps": {"type": "array"},
                    "resources": {"type": "array"},
                    "risks": {"type": "array"},
                    "costs": {"type": "object"},
                },
                "required": ["title", "steps"]
            },
            handler=self._generate_plan_document,
            tags=["document", "plan"],
        ))

    async def decompose_task(
        self,
        task: str,
        context: dict[str, Any],
    ) -> list[AgentStep]:
        """
        Decompose planning task into analysis steps.
        تقسيم مهمة التخطيط إلى خطوات تحليلية
        """
        field_id = context.get("field_id")
        farm_id = context.get("farm_id")

        # Detect planning type from task
        task_lower = task.lower()

        is_planting = any(w in task_lower for w in ["plant", "زراعة", "بذر"])
        is_rotation = any(w in task_lower for w in ["rotation", "تناوب"])
        is_season = any(w in task_lower for w in ["season", "موسم", "plan", "خطة"])

        steps = [
            # Always start with history analysis
            AgentStep(
                step_id=str(uuid.uuid4()),
                step_number=1,
                description="Analyze field history and past performance",
                description_ar="تحليل تاريخ الحقل والأداء السابق",
                tool_name="analyze_field_history",
                tool_input={"field_id": field_id, "years": 3},
            ),
        ]

        if is_rotation:
            steps.append(AgentStep(
                step_id=str(uuid.uuid4()),
                step_number=2,
                description="Evaluate crop rotation options",
                description_ar="تقييم خيارات التناوب المحصولي",
                tool_name="evaluate_rotation",
                tool_input={"field_id": field_id},
            ))

        if is_planting or is_season:
            steps.extend([
                AgentStep(
                    step_id=str(uuid.uuid4()),
                    step_number=len(steps) + 1,
                    description="Assess weather windows for operations",
                    description_ar="تقييم النوافذ الجوية للعمليات",
                    tool_name="assess_weather_window",
                    tool_input={"operation_type": "planting", "days_ahead": 14},
                ),
                AgentStep(
                    step_id=str(uuid.uuid4()),
                    step_number=len(steps) + 2,
                    description="Check resource availability",
                    description_ar="فحص توفر الموارد",
                    tool_name="check_resources",
                    tool_input={"farm_id": farm_id},
                ),
            ])

        # Always assess risks and costs
        steps.extend([
            AgentStep(
                step_id=str(uuid.uuid4()),
                step_number=len(steps) + 1,
                description="Calculate estimated costs",
                description_ar="حساب التكاليف المقدرة",
                tool_name="calculate_costs",
                tool_input={"operation_type": "seasonal_plan", "field_id": field_id},
            ),
            AgentStep(
                step_id=str(uuid.uuid4()),
                step_number=len(steps) + 2,
                description="Assess risks and mitigation strategies",
                description_ar="تقييم المخاطر واستراتيجيات التخفيف",
                tool_name="assess_risks",
                tool_input={"operation": {"type": "seasonal_plan"}, "field_id": field_id},
            ),
            # Final plan document
            AgentStep(
                step_id=str(uuid.uuid4()),
                step_number=len(steps) + 3,
                description="Generate execution plan document",
                description_ar="توليد وثيقة خطة التنفيذ",
                tool_name="generate_plan_document",
                tool_input={
                    "title": f"Execution Plan for {field_id or 'Farm'}",
                    "title_ar": f"خطة تنفيذ للحقل {field_id or 'المزرعة'}",
                },
            ),
        ])

        return steps

    async def validate_step_result(
        self,
        step: AgentStep,
        result: ToolResult,
        context: dict[str, Any],
    ) -> tuple[bool, str | None]:
        """Validate planning step result."""
        if not result.success:
            return False, f"Analysis step failed: {result.error}"

        # All read-only operations are valid if they return data
        if result.result is None:
            return False, "No data returned from analysis"

        return True, None

    async def create_plan(
        self,
        objective: str,
        context: dict[str, Any] | None = None,
    ) -> ExecutionPlan:
        """
        Convenience method to create an execution plan.
        طريقة مريحة لإنشاء خطة تنفيذ

        Args:
            objective: What needs to be planned
            context: Additional context

        Returns:
            ExecutionPlan ready for approval
        """
        context = context or {}

        # Run the planning workflow
        result = await self.run(task=objective, context=context)

        # Extract plan from result
        if result.get("success") and self.current_plan:
            return self.current_plan

        # Create basic plan from steps
        return ExecutionPlan(
            plan_id=str(uuid.uuid4()),
            title=objective[:100],
            title_ar=objective[:100],
            description=f"Execution plan for: {objective}",
            description_ar=f"خطة تنفيذ لـ: {objective}",
            steps=[s.to_dict() for s in self.steps],
            requires_approval=True,
        )

    # Tool handlers (read-only analysis)
    async def _analyze_field_history(
        self,
        field_id: str,
        years: int = 3,
    ) -> dict[str, Any]:
        """Analyze field history."""
        logger.info("analyzing_field_history", field_id=field_id, years=years)

        return {
            "field_id": field_id,
            "analysis_period_years": years,
            "crop_history": [
                {"season": "2025-winter", "crop": "wheat", "yield_t_ha": 4.5},
                {"season": "2024-summer", "crop": "fallow", "yield_t_ha": 0},
                {"season": "2024-winter", "crop": "barley", "yield_t_ha": 3.8},
            ],
            "average_yield_t_ha": 4.15,
            "soil_health_trend": "stable",
            "issues_reported": ["nitrogen_deficiency_2024", "water_stress_2025"],
            "recommendations_from_history": [
                "Increase nitrogen application by 10%",
                "Consider earlier irrigation start",
            ],
        }

    async def _check_resources(
        self,
        farm_id: str,
        resource_types: list[str] | None = None,
        date_range: dict[str, str] | None = None,
    ) -> dict[str, Any]:
        """Check resource availability."""
        logger.info("checking_resources", farm_id=farm_id)

        return {
            "farm_id": farm_id,
            "resources": {
                "water": {
                    "available": True,
                    "capacity_m3_day": 500,
                    "current_usage_pct": 60,
                    "status": "adequate",
                },
                "equipment": {
                    "tractor": {"available": True, "next_maintenance": "2026-02-15"},
                    "sprayer": {"available": True, "calibrated": True},
                    "harvester": {"available": False, "available_from": "2026-04-01"},
                },
                "labor": {
                    "permanent_workers": 5,
                    "seasonal_available": True,
                    "peak_season_covered": True,
                },
            },
            "constraints": ["Harvester not available until April"],
        }

    async def _assess_weather_window(
        self,
        operation_type: str,
        location: dict[str, float] | None = None,
        days_ahead: int = 14,
    ) -> dict[str, Any]:
        """Assess weather windows."""
        logger.info("assessing_weather", operation=operation_type)

        return {
            "operation_type": operation_type,
            "analysis_days": days_ahead,
            "optimal_windows": [
                {
                    "start": "2026-01-23",
                    "end": "2026-01-25",
                    "confidence": 0.85,
                    "conditions": "Clear, 15-20°C, low wind",
                },
                {
                    "start": "2026-01-28",
                    "end": "2026-01-30",
                    "confidence": 0.75,
                    "conditions": "Partly cloudy, 12-18°C",
                },
            ],
            "avoid_dates": ["2026-01-26", "2026-01-27"],
            "avoid_reason": "60% rain probability",
        }

    async def _evaluate_rotation(
        self,
        field_id: str,
        current_crop: str | None = None,
        season: str | None = None,
        constraints: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Evaluate crop rotation options."""
        logger.info("evaluating_rotation", field_id=field_id)

        return {
            "field_id": field_id,
            "current_crop": current_crop or "wheat",
            "rotation_options": [
                {
                    "crop": "legume (chickpea)",
                    "crop_ar": "بقوليات (حمص)",
                    "score": 92,
                    "benefits": ["Nitrogen fixation", "Break disease cycle"],
                    "benefits_ar": ["تثبيت النيتروجين", "كسر دورة المرض"],
                },
                {
                    "crop": "barley",
                    "crop_ar": "شعير",
                    "score": 78,
                    "benefits": ["Lower water requirement", "Similar management"],
                },
                {
                    "crop": "fallow",
                    "crop_ar": "بور",
                    "score": 65,
                    "benefits": ["Soil recovery", "Moisture conservation"],
                },
            ],
            "recommendation": "legume (chickpea)",
            "recommendation_ar": "بقوليات (حمص)",
        }

    async def _calculate_costs(
        self,
        operation_type: str,
        field_id: str | None = None,
        area_ha: float | None = None,
        inputs: list[dict[str, Any]] | None = None,
    ) -> dict[str, Any]:
        """Calculate operation costs."""
        logger.info("calculating_costs", operation=operation_type)

        area = area_ha or 8.5

        return {
            "operation_type": operation_type,
            "area_ha": area,
            "costs": {
                "seeds": {"amount": 1200 * area, "unit": "SAR"},
                "fertilizer": {"amount": 450 * area, "unit": "SAR"},
                "labor": {"amount": 300 * area, "unit": "SAR"},
                "equipment": {"amount": 200 * area, "unit": "SAR"},
                "water": {"amount": 150 * area, "unit": "SAR"},
            },
            "total_cost_sar": 2300 * area,
            "cost_per_ha_sar": 2300,
            "expected_revenue_sar": 8500 * area,
            "expected_profit_sar": 6200 * area,
            "roi_percent": 269,
        }

    async def _assess_risks(
        self,
        operation: dict[str, Any],
        field_id: str | None = None,
        timing: str | None = None,
    ) -> dict[str, Any]:
        """Assess operation risks."""
        logger.info("assessing_risks", operation=operation.get("type"))

        return {
            "operation": operation,
            "risk_level": "medium",
            "risks": [
                {
                    "risk": "Weather variability",
                    "risk_ar": "تقلب الطقس",
                    "probability": "medium",
                    "impact": "high",
                    "mitigation": "Monitor forecasts, flexible scheduling",
                    "mitigation_ar": "مراقبة التوقعات، جدولة مرنة",
                },
                {
                    "risk": "Pest outbreak",
                    "risk_ar": "تفشي الآفات",
                    "probability": "low",
                    "impact": "medium",
                    "mitigation": "Regular scouting, preventive treatment",
                },
                {
                    "risk": "Water shortage",
                    "risk_ar": "نقص المياه",
                    "probability": "low",
                    "impact": "high",
                    "mitigation": "Efficient irrigation, backup source",
                },
            ],
            "overall_risk_score": 45,
            "recommendation": "Proceed with standard precautions",
        }

    async def _generate_plan_document(
        self,
        title: str,
        title_ar: str | None = None,
        steps: list[dict[str, Any]] | None = None,
        resources: list[str] | None = None,
        risks: list[dict[str, Any]] | None = None,
        costs: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Generate formal plan document."""
        logger.info("generating_plan_document", title=title)

        # Gather data from previous steps
        gathered = getattr(self, 'gathered_data', {})

        plan = ExecutionPlan(
            plan_id=str(uuid.uuid4()),
            title=title,
            title_ar=title_ar or title,
            description="Comprehensive execution plan based on analysis",
            description_ar="خطة تنفيذ شاملة بناءً على التحليل",
            steps=steps or [s.to_dict() for s in self.steps],
            estimated_duration_minutes=120,
            risk_level="medium",
            requires_approval=True,
            resources_needed=resources or ["water", "labor", "equipment"],
        )

        self.current_plan = plan

        return {
            "plan": plan.to_dict(),
            "status": "ready_for_approval",
            "message": "Plan generated successfully. Awaiting approval.",
            "message_ar": "تم توليد الخطة بنجاح. في انتظار الموافقة.",
        }

    def _generate_summary(self, outputs: list[dict[str, Any]]) -> str:
        """Generate planning summary."""
        if self.current_plan:
            return f"""
## Execution Plan | خطة التنفيذ

**Title | العنوان:** {self.current_plan.title}
**العنوان:** {self.current_plan.title_ar}

**Risk Level | مستوى المخاطرة:** {self.current_plan.risk_level}
**Estimated Duration | المدة المقدرة:** {self.current_plan.estimated_duration_minutes} minutes

**Status:** Ready for approval | جاهز للموافقة

---
This plan was generated in read-only mode. No changes have been made.
تم توليد هذه الخطة في وضع القراءة فقط. لم يتم إجراء أي تغييرات.
"""

        return "Planning analysis completed. | اكتمل تحليل التخطيط."
