# Hadolint Configuration for SAHOOL Unified Platform
# Version: 15.0.0
# Dockerfile linting rules and exclusions

# ═══════════════════════════════════════════════════════════════════════════════
# IGNORED RULES
# ═══════════════════════════════════════════════════════════════════════════════
ignored:
  # DL3008: Pin versions in apt-get install
  # Rationale: Alpine apk and some base images handle this differently
  - DL3008
  
  # DL3013: Pin versions in pip install  
  # Rationale: We use requirements.txt for version pinning
  - DL3013
  
  # DL3018: Pin versions in apk add
  # Rationale: Alpine Linux manages this at the image level
  - DL3018
  
  # DL3059: Multiple consecutive RUN instructions
  # Rationale: Sometimes necessary for clarity and layer optimization
  - DL3059
  
  # SC2046: Quote this to prevent word splitting
  # Rationale: False positives in multi-line commands
  - SC2046
  
  # SC1091: Not following sourced file
  # Rationale: Files may not exist in build context
  - SC1091

# ═══════════════════════════════════════════════════════════════════════════════
# TRUSTED REGISTRIES
# ═══════════════════════════════════════════════════════════════════════════════
trustedRegistries:
  - docker.io
  - ghcr.io
  - gcr.io
  - registry.hub.docker.com
  - mcr.microsoft.com
  - quay.io

# ═══════════════════════════════════════════════════════════════════════════════
# STRICTNESS LEVEL
# ═══════════════════════════════════════════════════════════════════════════════
# Options: error, warning, info, style, ignore, none
failure-threshold: warning
