# ═══════════════════════════════════════════════════════════════════════════════
# Kube-linter Configuration for SAHOOL
# Defines security and best practice checks for Kubernetes manifests and Helm charts
# ═══════════════════════════════════════════════════════════════════════════════

checks:
  # Enable all default checks
  addAllBuiltIn: true

  # Exclude specific checks that may not apply
  exclude:
    # Allow services without selectors (for ExternalName services)
    - "no-extensions-v1beta"
    # Allow deprecated APIs in older charts (will be addressed separately)
    - "deprecated-service-account-field"

  # Include critical security checks
  include:
    - "dangling-service"
    - "default-service-account"
    - "deprecated-service-account-field"
    - "docker-sock"
    - "drop-net-raw-capability"
    - "env-var-secret"
    - "host-ipc"
    - "host-network"
    - "host-pid"
    - "mismatching-selector"
    - "no-anti-affinity"
    - "no-extensions-v1beta"
    - "no-liveness-probe"
    - "no-read-only-root-fs"
    - "no-readiness-probe"
    - "non-existent-service-account"
    - "privileged-container"
    - "privilege-escalation-container"
    - "required-annotation-email"
    - "required-label-owner"
    - "run-as-non-root"
    - "sensitive-host-mounts"
    - "ssh-port"
    - "unsafe-proc-mount"
    - "unsafe-sysctls"
    - "unset-cpu-requirements"
    - "unset-memory-requirements"
    - "writable-host-mount"

customChecks:
  # Check for resource limits
  - name: "require-resource-limits"
    template: "resource-requirements"
    params:
      requirementsType: "limits"
    remediation: "Set resource limits for all containers to prevent resource exhaustion"
    scope:
      objectKinds:
        - DeploymentLike

  # Check for resource requests
  - name: "require-resource-requests"
    template: "resource-requirements"
    params:
      requirementsType: "requests"
    remediation: "Set resource requests for proper scheduling and cluster planning"
    scope:
      objectKinds:
        - DeploymentLike

  # Require security context
  - name: "require-security-context"
    template: "security-context"
    params:
      mustHave:
        - "runAsNonRoot"
        - "runAsUser"
    remediation: "Add securityContext with runAsNonRoot and runAsUser to all containers"
    scope:
      objectKinds:
        - DeploymentLike
        - Pod

  # Check for image pull policy
  - name: "image-pull-policy-always"
    template: "image-pull-policy"
    params:
      policy: "Always"
    remediation: "Set imagePullPolicy to Always for production workloads"
    scope:
      objectKinds:
        - DeploymentLike

# Severity levels
severityThresholds:
  error: 3
  warning: 2

# Ignore paths
ignorePaths:
  - ".git/"
  - "node_modules/"
  - "archive/"
  - "vendor/"
  - "**/test/**"
  - "**/tests/**"
  - "**/*_test.yaml"
  - "**/*-test.yaml"

# Output format
format: "plain"
