# ═══════════════════════════════════════════════════════════════════════════════
# SAHOOL Platform Security Policies
# Comprehensive security configuration and policies
# ═══════════════════════════════════════════════════════════════════════════════

version: "1.0"
platform: "SAHOOL Unified v15"
last_updated: "2026-01-07"

# ─────────────────────────────────────────────────────────────────────────────
# Authentication Policies
# ─────────────────────────────────────────────────────────────────────────────

authentication:
  password_policy:
    min_length: 12
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_special_chars: true
    max_age_days: 90
    password_history: 5
    lockout_threshold: 5
    lockout_duration_minutes: 30

  mfa:
    enabled: true
    methods:
      - totp
      - sms
      - email
    grace_period_days: 7

  session:
    timeout_minutes: 30
    absolute_timeout_hours: 12
    concurrent_sessions: 3
    secure_cookie: true
    httponly_cookie: true
    samesite: "strict"

  jwt:
    algorithm: "RS256"
    access_token_ttl_minutes: 30
    refresh_token_ttl_days: 7
    issuer: "sahool-idp"
    audience: "sahool-platform"
    key_rotation_days: 90

# ─────────────────────────────────────────────────────────────────────────────
# Authorization Policies
# ─────────────────────────────────────────────────────────────────────────────

authorization:
  rbac:
    enabled: true
    default_role: "viewer"

  roles:
    - name: "admin"
      permissions:
        - "*:*:*"

    - name: "developer"
      permissions:
        - "app:*:read"
        - "app:*:write"
        - "logs:*:read"

    - name: "operator"
      permissions:
        - "app:*:read"
        - "monitoring:*:read"
        - "infrastructure:*:read"

    - name: "viewer"
      permissions:
        - "app:*:read"
        - "monitoring:*:read"

  abac:
    enabled: true
    attributes:
      - user.department
      - user.location
      - resource.classification
      - environment.time

# ─────────────────────────────────────────────────────────────────────────────
# Network Security Policies
# ─────────────────────────────────────────────────────────────────────────────

network:
  tls:
    min_version: "TLSv1.2"
    preferred_version: "TLSv1.3"
    cipher_suites:
      - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
      - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
      - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
      - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
    certificate_rotation_days: 90
    certificate_expiry_warning_days: 30

  firewall:
    default_policy: "deny"
    allowed_ports:
      - port: 80
        protocol: "tcp"
        source: "anywhere"
        description: "HTTP (redirect to HTTPS)"
      - port: 443
        protocol: "tcp"
        source: "anywhere"
        description: "HTTPS"
      - port: 22
        protocol: "tcp"
        source: "internal"
        description: "SSH (internal only)"

  rate_limiting:
    enabled: true
    global:
      requests_per_minute: 1000
      requests_per_hour: 10000
    per_endpoint:
      auth_login:
        requests_per_minute: 10
        burst: 20
      api_read:
        requests_per_minute: 100
        burst: 200
      api_write:
        requests_per_minute: 50
        burst: 100

  ddos_protection:
    enabled: true
    syn_flood_protection: true
    connection_rate_limit: 100
    max_connections_per_ip: 50

# ─────────────────────────────────────────────────────────────────────────────
# Data Protection Policies
# ─────────────────────────────────────────────────────────────────────────────

data_protection:
  classification:
    levels:
      - name: "public"
        encryption_required: false
        backup_required: true
        retention_days: 365

      - name: "internal"
        encryption_required: true
        backup_required: true
        retention_days: 730

      - name: "confidential"
        encryption_required: true
        backup_required: true
        retention_days: 2555
        access_logging: true

      - name: "restricted"
        encryption_required: true
        backup_required: true
        retention_days: 2555
        access_logging: true
        mfa_required: true

  encryption:
    at_rest:
      algorithm: "AES-256-GCM"
      key_rotation_days: 90

    in_transit:
      required: true
      min_tls_version: "TLSv1.2"

    database:
      enabled: true
      algorithm: "AES-256"
      transparent_data_encryption: true

  masking:
    enabled: true
    fields:
      - "ssn"
      - "credit_card"
      - "password"
      - "api_key"
      - "secret"

  tokenization:
    enabled: true
    sensitive_fields:
      - "payment_info"
      - "personal_identifiers"

# ─────────────────────────────────────────────────────────────────────────────
# Container Security Policies
# ─────────────────────────────────────────────────────────────────────────────

container_security:
  base_images:
    allowed_registries:
      - "docker.io"
      - "ghcr.io"
      - "gcr.io"
    prohibited_tags:
      - "latest"
    scan_on_build: true
    scan_on_deploy: true

  runtime:
    run_as_root: false
    privileged_mode: false
    read_only_root_fs: true
    no_new_privileges: true

    capabilities:
      drop_all: true
      allowed:
        - "NET_BIND_SERVICE"
        - "CHOWN"
        - "SETGID"
        - "SETUID"

    seccomp:
      enabled: true
      profile: "/etc/docker/seccomp-profile.json"

    apparmor:
      enabled: true
      profile: "docker-sahool"

    resource_limits:
      cpu: "1.0"
      memory: "512Mi"
      pids: 100

  image_scanning:
    enabled: true
    severity_threshold: "HIGH"
    fail_on_critical: true
    scanners:
      - "trivy"
      - "grype"
    scan_schedule: "0 2 * * *"

# ─────────────────────────────────────────────────────────────────────────────
# Secrets Management Policies
# ─────────────────────────────────────────────────────────────────────────────

secrets_management:
  storage:
    provider: "vault"
    encryption: "AES-256-GCM"

  rotation:
    enabled: true
    schedules:
      database_passwords:
        frequency_days: 90
        notification_days_before: 7
      api_keys:
        frequency_days: 180
        notification_days_before: 14
      jwt_keys:
        frequency_days: 90
        notification_days_before: 7
      tls_certificates:
        frequency_days: 60
        notification_days_before: 30

  access:
    min_privilege: true
    just_in_time: true
    approval_required: true
    audit_logging: true

  detection:
    scan_commits: true
    scan_containers: true
    scan_logs: false
    scanners:
      - "gitleaks"
      - "trufflehog"

# ─────────────────────────────────────────────────────────────────────────────
# Logging and Monitoring Policies
# ─────────────────────────────────────────────────────────────────────────────

logging:
  security_events:
    enabled: true
    retention_days: 365

  events_to_log:
    - authentication_success
    - authentication_failure
    - authorization_failure
    - privilege_escalation
    - configuration_change
    - secret_access
    - data_access
    - api_access
    - admin_action

  log_format: "json"

  sensitive_data:
    redact_passwords: true
    redact_tokens: true
    redact_api_keys: true
    redact_credit_cards: true

  siem_integration:
    enabled: false
    provider: "elastic"

monitoring:
  security_metrics:
    - failed_login_attempts
    - api_error_rate
    - certificate_expiry
    - vulnerability_count
    - patch_compliance

  alerting:
    channels:
      - email
      - slack
      - pagerduty

    rules:
      - name: "Critical Vulnerability Detected"
        severity: "critical"
        condition: "vulnerability.severity == 'CRITICAL'"
        notification: "immediate"

      - name: "Multiple Failed Logins"
        severity: "high"
        condition: "failed_logins > 5 in 5m"
        notification: "immediate"

      - name: "Certificate Expiring Soon"
        severity: "medium"
        condition: "certificate.days_until_expiry < 30"
        notification: "daily"

# ─────────────────────────────────────────────────────────────────────────────
# Compliance Policies
# ─────────────────────────────────────────────────────────────────────────────

compliance:
  frameworks:
    - name: "CIS Docker Benchmark"
      version: "1.4.0"
      enabled: true

    - name: "CIS PostgreSQL Benchmark"
      version: "1.0"
      enabled: true

    - name: "OWASP Top 10"
      version: "2021"
      enabled: true

    - name: "PCI DSS"
      version: "3.2.1"
      enabled: false

  audit:
    frequency: "monthly"
    automated: true
    report_format: "markdown"

  vulnerability_management:
    scan_frequency: "daily"
    patch_window_days: 30
    critical_patch_window_days: 7

  incident_response:
    enabled: true
    escalation_matrix:
      - severity: "critical"
        response_time_minutes: 15
        notification: ["security-team", "cto", "ceo"]
      - severity: "high"
        response_time_minutes: 60
        notification: ["security-team", "devops-team"]
      - severity: "medium"
        response_time_hours: 4
        notification: ["security-team"]
      - severity: "low"
        response_time_hours: 24
        notification: ["security-team"]

# ─────────────────────────────────────────────────────────────────────────────
# Backup and Recovery Policies
# ─────────────────────────────────────────────────────────────────────────────

backup_recovery:
  backup:
    frequency: "daily"
    retention_days: 30
    encryption: true
    offsite: true
    verification: true

  recovery:
    rto_hours: 4
    rpo_hours: 24
    testing_frequency: "quarterly"

  disaster_recovery:
    enabled: true
    failover_site: true
    data_replication: "async"

# ─────────────────────────────────────────────────────────────────────────────
# Third-Party Security Policies
# ─────────────────────────────────────────────────────────────────────────────

third_party:
  dependency_management:
    scan_frequency: "weekly"
    auto_update_minor: false
    auto_update_patch: false
    approval_required: true

  vendor_assessment:
    required: true
    assessment_frequency_months: 12
    minimum_security_score: 80

  api_security:
    authentication_required: true
    rate_limiting: true
    input_validation: true
    output_sanitization: true

# ─────────────────────────────────────────────────────────────────────────────
# Security Training and Awareness
# ─────────────────────────────────────────────────────────────────────────────

security_training:
  mandatory: true
  frequency_months: 12

  topics:
    - secure_coding
    - phishing_awareness
    - password_hygiene
    - incident_response
    - data_protection

  assessment:
    required: true
    passing_score: 80

  specialized_training:
    security_champions:
      frequency_months: 6
      topics:
        - threat_modeling
        - security_testing
        - vulnerability_management
