_format_version: "3.0"
_transform: true

# SAHOOL Kong Gateway - Declarative Configuration
# All services with rate limiting, health checks, and request transformation

services:
  # Field Operations Service
  - name: field-ops
    url: http://field-service:8080
    connect_timeout: 5000
    read_timeout: 60000
    write_timeout: 60000
    retries: 3
    routes:
      - name: field-ops-route
        paths:
          - /api/v1/fields
          - /api/field-ops
        strip_path: false
        preserve_host: true
    plugins:
      - name: rate-limiting
        config:
          minute: 1000
          hour: 50000
          policy: redis
          redis_host: redis
          redis_port: 6379
          redis_password: ${REDIS_PASSWORD}
          redis_database: 1
          redis_timeout: 2000
          fault_tolerant: true
          hide_client_headers: false
      - name: request-transformer
        config:
          add:
            headers:
              - "X-Service-Name:field-ops"
              - "X-Service-Version:15.5.0"
      - name: cors
        config:
          origins:
            - https://sahool.app
            - https://admin.sahool.app
            - https://api.sahool.app
            - http://localhost:3000
            - http://localhost:5173
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Authorization
            - Content-Type
            - X-Request-ID
            - X-Tenant-ID
          credentials: true
          max_age: 3600

  # Satellite/NDVI Service
  - name: satellite-service
    url: http://satellite-service:8090
    connect_timeout: 5000
    read_timeout: 120000
    write_timeout: 60000
    retries: 2
    routes:
      - name: satellite-route
        paths:
          - /api/v1/satellite
          - /api/v1/ndvi
        strip_path: false
    plugins:
      - name: rate-limiting
        config:
          minute: 500
          hour: 25000
          policy: redis
          redis_host: redis
          redis_port: 6379
          redis_password: ${REDIS_PASSWORD}
          redis_database: 1
          redis_timeout: 2000
          fault_tolerant: true
          hide_client_headers: false
      - name: request-transformer
        config:
          add:
            headers:
              - "X-Service-Name:satellite-service"

  # Virtual Sensors Service
  - name: virtual-sensors
    url: http://virtual-sensors:8085
    connect_timeout: 5000
    read_timeout: 30000
    retries: 3
    routes:
      - name: virtual-sensors-route
        paths:
          - /api/v1/sensors
          - /api/v1/virtual-sensors
        strip_path: false
    plugins:
      - name: rate-limiting
        config:
          minute: 2000
          hour: 100000
          policy: redis
          redis_host: redis
          redis_port: 6379
          redis_password: ${REDIS_PASSWORD}
          redis_database: 1
          redis_timeout: 2000
          fault_tolerant: true
          hide_client_headers: false

  # Yield Prediction Service
  - name: yield-prediction
    url: http://yield-prediction:8091
    connect_timeout: 5000
    read_timeout: 60000
    retries: 2
    routes:
      - name: yield-route
        paths:
          - /api/v1/yield
        strip_path: false
    plugins:
      - name: rate-limiting
        config:
          minute: 300
          hour: 15000
          policy: redis
          redis_host: redis
          redis_port: 6379
          redis_password: ${REDIS_PASSWORD}
          redis_database: 1
          redis_timeout: 2000
          fault_tolerant: true
          hide_client_headers: false

  # LAI Estimation Service
  - name: lai-estimation
    url: http://lai-estimation:8093
    connect_timeout: 5000
    read_timeout: 60000
    retries: 2
    routes:
      - name: lai-route
        paths:
          - /api/v1/lai
        strip_path: false
    plugins:
      - name: rate-limiting
        config:
          minute: 500
          hour: 25000
          policy: redis
          redis_host: redis
          redis_port: 6379
          redis_password: ${REDIS_PASSWORD}
          redis_database: 1
          redis_timeout: 2000
          fault_tolerant: true
          hide_client_headers: false

  # Irrigation Smart Service
  - name: irrigation-smart
    url: http://irrigation-smart:8086
    connect_timeout: 5000
    read_timeout: 30000
    retries: 3
    routes:
      - name: irrigation-route
        paths:
          - /api/v1/irrigation
        strip_path: false
    plugins:
      - name: rate-limiting
        config:
          minute: 1000
          hour: 50000
          policy: redis
          redis_host: redis
          redis_port: 6379
          redis_password: ${REDIS_PASSWORD}
          redis_database: 1
          redis_timeout: 2000
          fault_tolerant: true
          hide_client_headers: false

  # Notification Service
  - name: notification-service
    url: http://notification-service:8083
    connect_timeout: 3000
    read_timeout: 10000
    retries: 2
    routes:
      - name: notification-route
        paths:
          - /api/v1/notifications
        strip_path: false
    plugins:
      - name: rate-limiting
        config:
          minute: 5000
          hour: 250000
          policy: redis
          redis_host: redis
          redis_port: 6379
          redis_password: ${REDIS_PASSWORD}
          redis_database: 1
          redis_timeout: 2000
          fault_tolerant: true
          hide_client_headers: false

  # Crop Growth Timing Service
  - name: crop-growth-timing
    url: http://crop-growth-timing:8098
    connect_timeout: 5000
    read_timeout: 45000
    retries: 2
    routes:
      - name: crop-timing-route
        paths:
          - /api/v1/crop-timing
          - /api/v1/growth
        strip_path: false
    plugins:
      - name: rate-limiting
        config:
          minute: 500
          hour: 25000
          policy: redis
          redis_host: redis
          redis_port: 6379
          redis_password: ${REDIS_PASSWORD}
          redis_database: 1
          redis_timeout: 2000
          fault_tolerant: true
          hide_client_headers: false

  # Weather Service
  - name: weather-service
    url: http://weather-advanced:8092
    connect_timeout: 5000
    read_timeout: 30000
    retries: 3
    routes:
      - name: weather-route
        paths:
          - /api/v1/weather
        strip_path: false
    plugins:
      - name: rate-limiting
        config:
          minute: 1000
          hour: 50000
          policy: redis
          redis_host: redis
          redis_port: 6379
          redis_password: ${REDIS_PASSWORD}
          redis_database: 1
          redis_timeout: 2000
          fault_tolerant: true
          hide_client_headers: false

# Global plugins
plugins:
  - name: correlation-id
    config:
      header_name: X-Request-ID
      generator: uuid
      echo_downstream: true
