# Argo Rollouts Application
# ==========================
# Enables progressive delivery with canary and blue-green deployments
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.35.0
    chart: argo-rollouts
    helm:
      values: |
        controller:
          replicas: 2
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
        dashboard:
          enabled: true
          ingress:
            enabled: true
            hosts:
              - rollouts.sahool.io
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
