apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feature-flags
  namespace: argocd
spec:
  project: sahool
  source:
    repoURL: REPLACE_WITH_YOUR_REPO_URL
    targetRevision: main
    path: gitops/feature-flags/flagd
  destination:
    server: https://kubernetes.default.svc
    namespace: feature-flags
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
