apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sahool-idp-root
  namespace: argocd
spec:
  project: sahool
  source:
    repoURL: REPLACE_WITH_YOUR_REPO_URL
    targetRevision: main
    path: gitops/idp/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
