apiVersion: v2
name: iot-service
description: SAHOOL Iot Service - Microservice
type: application
version: 1.0.0
appVersion: "16.0.0"
keywords:
  - sahool
  - iot
  - microservice
maintainers:
  - name: KAFAAT
    email: platform@kafaat.sa
