# ============================================================================
# CORS Configuration - Staging Environment
# تكوين CORS - بيئة الاختبار
# ============================================================================
# Staging environment allows staging domains and limited localhost access
# بيئة الاختبار تسمح نطاقات الاختبار ووصول محدود لـ localhost
# ============================================================================

cors:
  origins:
    - https://staging.sahool.app
    - https://staging-api.sahool.app
    - https://staging-admin.sahool.app
    - https://qa.sahool.app
    - http://localhost:3000
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
  headers:
    - Accept
    - Accept-Version
    - Content-Length
    - Content-MD5
    - Content-Type
    - Date
    - Authorization
    - X-Auth-Token
    - X-Request-ID
    - X-API-Key
  exposed_headers:
    - X-Auth-Token
    - X-Request-ID
    - X-RateLimit-Limit
    - X-RateLimit-Remaining
  credentials: true
  max_age: 7200
  preflight_continue: false
