# ============================================================================
# CORS Configuration - Development Environment
# تكوين CORS - بيئة التطوير
# ============================================================================
# Development environment allows localhost and development domains
# بيئة التطوير تسمح localhost ونطاقات التطوير
# ============================================================================

cors:
  origins:
    - http://localhost:3000
    - http://localhost:3001
    - http://localhost:8080
    - http://localhost:8000
    - http://127.0.0.1:3000
    - http://127.0.0.1:8080
    - https://dev.sahool.app
    - https://dev-api.sahool.app
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
    - HEAD
  headers:
    - Accept
    - Accept-Version
    - Content-Length
    - Content-MD5
    - Content-Type
    - Date
    - Authorization
    - X-Auth-Token
    - X-Request-ID
    - X-API-Key
    - X-Client-Version
  exposed_headers:
    - X-Auth-Token
    - X-Request-ID
    - X-RateLimit-Limit
    - X-RateLimit-Remaining
    - X-RateLimit-Reset
  credentials: true
  max_age: 3600
  preflight_continue: false
