# ============================================================================
# CORS Configuration - Production Environment
# تكوين CORS - بيئة الإنتاج
# ============================================================================
# Production environment allows only production domains - NO localhost
# بيئة الإنتاج تسمح فقط نطاقات الإنتاج - بدون localhost
# ============================================================================

cors:
  origins:
    - https://sahool.app
    - https://www.sahool.app
    - https://api.sahool.app
    - https://admin.sahool.app
    - https://app.sahool.com
    - https://api.sahool.com
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
  headers:
    - Accept
    - Accept-Version
    - Content-Length
    - Content-Type
    - Date
    - Authorization
    - X-Auth-Token
    - X-Request-ID
  exposed_headers:
    - X-Request-ID
    - X-RateLimit-Limit
    - X-RateLimit-Remaining
  credentials: true
  max_age: 86400
  preflight_continue: false
