/**
 * Disaster Assessment Feature - Mock Data (Development Fallback)
 * بيانات وهمية لتقييم الكوارث
 *
 * Separated from the API layer to reduce client bundle size.
 * This data is used as fallback when the API is unavailable.
 */

import type { RiskAssessment, DisasterEvent, DisasterStats } from './types';

export const MOCK_RISKS: RiskAssessment[] = [
  {
    id: '1',
    type: 'drought',
    typeAr: 'جفاف',
    riskLevel: 'medium',
    affectedArea: 'Central Region',
    affectedAreaAr: 'المنطقة الوسطى',
    probability: 45,
    potentialLoss: 150000,
    currency: 'SAR',
    mitigationPlan: 'Activate emergency irrigation reserves',
    mitigationPlanAr: 'تفعيل احتياطيات الري الطارئة',
    lastUpdated: '2026-01-25',
    metadata: {},
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-01-25T08:00:00Z',
  },
  {
    id: '2',
    type: 'frost',
    typeAr: 'صقيع',
    riskLevel: 'high',
    affectedArea: 'Northern Farms',
    affectedAreaAr: 'المزارع الشمالية',
    probability: 70,
    potentialLoss: 85000,
    currency: 'SAR',
    mitigationPlan: 'Deploy frost protection covers',
    mitigationPlanAr: 'نشر أغطية الحماية من الصقيع',
    lastUpdated: '2026-01-25',
    metadata: {},
    createdAt: '2026-01-22T09:00:00Z',
    updatedAt: '2026-01-25T07:00:00Z',
  },
  {
    id: '3',
    type: 'pest',
    typeAr: 'آفات',
    riskLevel: 'low',
    affectedArea: 'Al-Kharj Fields',
    affectedAreaAr: 'حقول الخرج',
    probability: 25,
    potentialLoss: 45000,
    currency: 'SAR',
    lastUpdated: '2026-01-24',
    metadata: {},
    createdAt: '2026-01-15T14:00:00Z',
    updatedAt: '2026-01-24T11:00:00Z',
  },
  {
    id: '4',
    type: 'storm',
    typeAr: 'عاصفة',
    riskLevel: 'critical',
    affectedArea: 'Eastern Province',
    affectedAreaAr: 'المنطقة الشرقية',
    probability: 85,
    potentialLoss: 320000,
    currency: 'SAR',
    mitigationPlan: 'Secure equipment, harvest ripe crops immediately',
    mitigationPlanAr: 'تأمين المعدات، حصاد المحاصيل الناضجة فوراً',
    lastUpdated: '2026-01-25',
    metadata: {},
    createdAt: '2026-01-25T05:00:00Z',
    updatedAt: '2026-01-25T10:00:00Z',
  },
];

export const MOCK_EVENTS: DisasterEvent[] = [
  {
    id: '1',
    type: 'storm',
    typeAr: 'عاصفة رملية',
    date: '2026-01-20',
    location: 'Qassim Region',
    locationAr: 'منطقة القصيم',
    affectedArea: 150,
    areaUnit: 'hectares',
    severity: 'moderate',
    status: 'resolved',
    damageEstimate: 25000,
    currency: 'SAR',
    description: 'Sandstorm causing minor crop damage',
    descriptionAr: 'عاصفة رملية تسببت في أضرار طفيفة للمحاصيل',
    metadata: {},
    createdAt: '2026-01-20T14:00:00Z',
    updatedAt: '2026-01-22T10:00:00Z',
  },
  {
    id: '2',
    type: 'flood',
    typeAr: 'سيول',
    date: '2026-01-18',
    location: 'Asir Mountains',
    locationAr: 'جبال عسير',
    affectedArea: 80,
    areaUnit: 'hectares',
    severity: 'severe',
    status: 'monitoring',
    damageEstimate: 180000,
    currency: 'SAR',
    description: 'Flash flooding from heavy rainfall',
    descriptionAr: 'فيضانات مفاجئة من الأمطار الغزيرة',
    affectedCrops: ['vegetables', 'fruits'],
    metadata: {},
    createdAt: '2026-01-18T08:00:00Z',
    updatedAt: '2026-01-24T16:00:00Z',
  },
];

export const MOCK_STATS: DisasterStats = {
  activeRisks: 4,
  criticalRisks: 2,
  totalPotentialLoss: 600000,
  activeEvents: 1,
  totalDamage: 205000,
  eventsThisYear: 2,
  byType: {
    drought: 1,
    frost: 1,
    pest: 1,
    storm: 1,
    flood: 0,
    disease: 0,
    fire: 0,
    other: 0,
  },
  byRiskLevel: {
    low: 1,
    medium: 1,
    high: 1,
    critical: 1,
  },
  recentAlerts: 3,
};
