"""
Task Service Package - حزمة خدمة المهام

This package provides the task management functionality for SAHOOL.
"""

from .exceptions import (
    TaskServiceError,
    ErrorCode,
    TaskNotFoundError,
    TaskAlreadyExistsError,
    TaskInvalidStatusError,
    TaskInvalidTransitionError,
    TaskCreationError,
    ValidationError,
    InvalidFieldIdError,
    InvalidDateFormatError,
    InvalidTimeFormatError,
    MetadataTooLargeError,
    ExternalServiceError,
    AstronomicalServiceError,
    AstronomicalServiceTimeoutError,
    FieldServiceError,
    NdviServiceError,
    NotificationServiceError,
    DatabaseError,
    DatabaseConnectionError,
    CacheError,
    CacheConnectionError,
    UnauthorizedError,
    ForbiddenError,
    InvalidTenantError,
)

from .validators import (
    MAX_METADATA_SIZE_BYTES,
    FIELD_ID_PATTERN,
    TIME_FORMAT_PATTERN,
    DATE_FORMAT_PATTERN,
    validate_field_id,
    validate_scheduled_time,
    validate_date_string,
    validate_metadata_size,
    sanitize_for_log,
    sanitize_field_id_for_url,
    scheduled_time_validator,
    field_id_validator,
    metadata_validator,
    date_string_validator,
    validate_task_create_data,
)

from .cache import (
    InMemoryCache,
    CacheAdapter,
    AstronomicalCache,
    TaskCache,
    get_redis_client,
    close_redis,
)

from .task_utils import (
    TaskType,
    TaskPriority,
    TaskStatus,
    TaskCreateData,
    generate_task_id,
    create_task_model,
    db_task_to_dict,
    calculate_ndvi_priority,
    generate_ndvi_task_content,
    get_due_date_for_priority,
    get_activity_translation,
    get_task_type_activity,
    fetch_field_manager,
    fetch_astronomical_best_days,
    fetch_astronomical_daily_data,
    fetch_astronomical_data,
    enrich_task_with_astronomy,
    send_task_notification,
)

__all__ = [
    # Exceptions
    "TaskServiceError",
    "ErrorCode",
    "TaskNotFoundError",
    "TaskAlreadyExistsError",
    "TaskInvalidStatusError",
    "TaskInvalidTransitionError",
    "TaskCreationError",
    "ValidationError",
    "InvalidFieldIdError",
    "InvalidDateFormatError",
    "InvalidTimeFormatError",
    "MetadataTooLargeError",
    "ExternalServiceError",
    "AstronomicalServiceError",
    "AstronomicalServiceTimeoutError",
    "FieldServiceError",
    "NdviServiceError",
    "NotificationServiceError",
    "DatabaseError",
    "DatabaseConnectionError",
    "CacheError",
    "CacheConnectionError",
    "UnauthorizedError",
    "ForbiddenError",
    "InvalidTenantError",
    # Validators
    "MAX_METADATA_SIZE_BYTES",
    "FIELD_ID_PATTERN",
    "TIME_FORMAT_PATTERN",
    "DATE_FORMAT_PATTERN",
    "validate_field_id",
    "validate_scheduled_time",
    "validate_date_string",
    "validate_metadata_size",
    "sanitize_for_log",
    "sanitize_field_id_for_url",
    "scheduled_time_validator",
    "field_id_validator",
    "metadata_validator",
    "date_string_validator",
    "validate_task_create_data",
    # Cache
    "InMemoryCache",
    "CacheAdapter",
    "AstronomicalCache",
    "TaskCache",
    "get_redis_client",
    "close_redis",
    # Task Utilities
    "TaskType",
    "TaskPriority",
    "TaskStatus",
    "TaskCreateData",
    "generate_task_id",
    "create_task_model",
    "db_task_to_dict",
    "calculate_ndvi_priority",
    "generate_ndvi_task_content",
    "get_due_date_for_priority",
    "get_activity_translation",
    "get_task_type_activity",
    "fetch_field_manager",
    "fetch_astronomical_best_days",
    "fetch_astronomical_daily_data",
    "fetch_astronomical_data",
    "enrich_task_with_astronomy",
    "send_task_notification",
]
