-- ═══════════════════════════════════════════════════════════════════════════════
-- Migration: Fix NOT NULL columns without DEFAULT values
-- إصلاح أعمدة بدون قيم افتراضية (إضافة DEFAULT للأعمدة الإلزامية)
-- Purpose: Add DEFAULT now() to updatedAt columns generated by Prisma @updatedAt
--          which lack SQL-level defaults. Prevents INSERT failures outside ORM.
-- Drift Report: 7d5dc4c6-bc6
-- ═══════════════════════════════════════════════════════════════════════════════

-- disaster_reports.updated_at: NOT NULL without DEFAULT (Prisma @updatedAt)
ALTER TABLE "disaster_reports" ALTER COLUMN "updated_at" SET DEFAULT now();

-- disaster_alerts.updated_at: NOT NULL without DEFAULT
ALTER TABLE "disaster_alerts" ALTER COLUMN "updated_at" SET DEFAULT now();

-- field_assessments.updated_at: NOT NULL without DEFAULT
ALTER TABLE "field_assessments" ALTER COLUMN "updated_at" SET DEFAULT now();

-- alert_subscriptions.updated_at: NOT NULL without DEFAULT
ALTER TABLE "alert_subscriptions" ALTER COLUMN "updated_at" SET DEFAULT now();

-- ═══════════════════════════════════════════════════════════════════════════════
-- Tenant Isolation Verification
-- التحقق من عزل المستأجر
-- All models in this service have tenant_id (required, VARCHAR 100):
--   - DisasterReport     ✅
--   - DisasterAlert      ✅
--   - FieldAssessment    ✅
--   - AlertSubscription  ✅
-- ═══════════════════════════════════════════════════════════════════════════════
