/**
 * Marketplace Feature - Mock Data (Development Fallback)
 * بيانات وهمية للسوق الزراعي
 *
 * Separated from the API layer to reduce client bundle size.
 * This data is used as fallback when the API is unavailable.
 */

import type { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Organic Wheat Seeds',
    nameAr: 'بذور قمح عضوية',
    description: 'High-quality organic wheat seeds, suitable for various soil types',
    descriptionAr: 'بذور قمح عضوية عالية الجودة، مناسبة لأنواع التربة المختلفة',
    category: 'seeds',
    price: 150,
    currency: 'SAR',
    unit: 'kg',
    unitAr: 'كجم',
    status: 'available',
    stock: 500,
    imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400',
    sellerId: 'seller1',
    sellerName: 'مؤسسة البذور الزراعية',
    sellerRating: 4.5,
    location: {
      city: 'Riyadh',
      cityAr: 'الرياض',
      region: 'Central',
      regionAr: 'الوسطى',
    },
    tags: ['organic', 'wheat', 'seeds'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'NPK Fertilizer 20-20-20',
    nameAr: 'سماد NPK 20-20-20',
    description: 'Balanced NPK fertilizer for all crops',
    descriptionAr: 'سماد NPK متوازن لجميع المحاصيل',
    category: 'fertilizers',
    price: 85,
    currency: 'SAR',
    unit: 'bag (25kg)',
    unitAr: 'كيس (25 كجم)',
    status: 'available',
    stock: 200,
    imageUrl: 'https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=400',
    sellerId: 'seller2',
    sellerName: 'الأسمدة الحديثة',
    sellerRating: 4.8,
    location: {
      city: 'Jeddah',
      cityAr: 'جدة',
      region: 'Western',
      regionAr: 'الغربية',
    },
    tags: ['fertilizer', 'NPK', 'nutrients'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Drip Irrigation Kit',
    nameAr: 'مجموعة الري بالتنقيط',
    description: 'Complete drip irrigation system for 1 hectare',
    descriptionAr: 'نظام ري بالتنقيط متكامل لمساحة هكتار واحد',
    category: 'equipment',
    price: 2500,
    currency: 'SAR',
    unit: 'set',
    unitAr: 'طقم',
    status: 'available',
    stock: 50,
    imageUrl: 'https://images.unsplash.com/photo-1563514227147-6d2ff665a6a0?w=400',
    sellerId: 'seller3',
    sellerName: 'أنظمة الري الحديثة',
    sellerRating: 4.9,
    location: {
      city: 'Dammam',
      cityAr: 'الدمام',
      region: 'Eastern',
      regionAr: 'الشرقية',
    },
    tags: ['irrigation', 'drip', 'equipment'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Organic Pesticide',
    nameAr: 'مبيد حشري عضوي',
    description: 'Safe organic pesticide for vegetable crops',
    descriptionAr: 'مبيد حشري عضوي آمن للخضروات',
    category: 'pesticides',
    price: 120,
    currency: 'SAR',
    unit: 'liter',
    unitAr: 'لتر',
    status: 'available',
    stock: 300,
    imageUrl: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400',
    sellerId: 'seller1',
    sellerName: 'مؤسسة البذور الزراعية',
    sellerRating: 4.5,
    location: {
      city: 'Riyadh',
      cityAr: 'الرياض',
      region: 'Central',
      regionAr: 'الوسطى',
    },
    tags: ['organic', 'pesticide', 'safe'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const MOCK_CATEGORIES = [
  { id: 'seeds', name: 'Seeds', nameAr: 'البذور', count: 45 },
  { id: 'fertilizers', name: 'Fertilizers', nameAr: 'الأسمدة', count: 32 },
  { id: 'pesticides', name: 'Pesticides', nameAr: 'المبيدات', count: 28 },
  { id: 'equipment', name: 'Equipment', nameAr: 'المعدات', count: 56 },
  { id: 'tools', name: 'Tools', nameAr: 'الأدوات', count: 89 },
  { id: 'irrigation', name: 'Irrigation', nameAr: 'الري', count: 23 },
];
