apiVersion: v2
name: irrigation-smart
description: SAHOOL Irrigation Smart - Microservice
type: application
version: 1.0.0
appVersion: "16.0.0"
keywords:
  - sahool
  - irrigation
  - microservice
maintainers:
  - name: KAFAAT
    email: platform@kafaat.sa
