# SAHOOL Field App Build Configuration
# ملف إعدادات توليد الكود
# Simplified: Let builders auto-discover files with annotations

targets:
  $default:
    builders:
      # JSON Serializable options only (auto-discovers @JsonSerializable)
      json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false

      # Drift options only (auto-discovers @DriftDatabase)
      drift_dev:
        options:
          store_date_time_values_as_text: true

      # Freezed: no config needed, auto-discovers @freezed

# Global excludes for all builders
global_options:
  source_gen:combining_builder:
    generate_for:
      exclude:
        - "test/**"
        - "**/*.mocks.dart"
