# SAHOOL Field App Build Configuration
# Minimal configuration - let build_runner auto-discover everything

targets:
  $default:
    builders:
      # Drift database options
      drift_dev:
        options:
          store_date_time_values_as_text: true

      # JSON serializable options
      json_serializable:
        options:
          explicit_to_json: true
