# SPDX-License-Identifier: Proprietary
# Copyright (c) 2026 KAFAAT - SAHOOL Platform
"""PROSAIL LUT inversion — see ADR-015.

Forward model is provided by ``shared.process_models.radiative_transfer``;
this module adds the **inversion** path on top of it:

    LUT generation → KD-tree retrieval → uncertainty quantification

LUT artifacts are persisted to MinIO (regenerated by a scheduled job).
The ``digital-twin-engine`` service (port 8253) exposes this via
``/api/v1/twin/prosail/invert`` (sync) and ``/batch`` (async).

Phase 4 implementation: pure-Python KD-tree retrieval (see
:mod:`shared.process_models.kd_tree`) with a brute-force fallback for
diagnostics and small-LUT regression tests. The KD-tree path is the
default and matches the ADR text; for the typical SAHOOL grid (≤ 5 axes
× 8 levels = 32 768 entries × ≤ 6 bands) build cost is ~50 ms and per
query is sub-millisecond.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any

from .kd_tree import KDTree
from .radiative_transfer import (
    CanopyParameters,
    LeafOpticalProperties,
    prospect_reflectance,
    sail_canopy_reflectance,
)

#: Default reflectance bands compared during retrieval.
_DEFAULT_BANDS = ("blue", "green", "red", "red_edge", "nir", "swir")
_DEFAULT_TOP_K = 10  # k-NN size for uncertainty quantification


@dataclass(frozen=True)
class ProsailGeometry:
    """Sun / view geometry required for a physically meaningful inversion."""

    sun_zenith_deg: float
    view_zenith_deg: float
    relative_azimuth_deg: float


@dataclass(frozen=True)
class ProsailRetrieval:
    """Inversion output with uncertainty bands."""

    parameters: dict[str, float]  # e.g. {"LAI": 3.2, "Cab": 45.0, "Cw": 0.012}
    uncertainty: dict[str, float]  # 1-sigma per parameter
    diagnostics: dict[str, Any] = field(default_factory=dict)


@dataclass
class ProsailLUT:
    """In-memory PROSAIL look-up table.

    ``parameters`` is a list of dicts with the canopy parameters used to
    build each entry; ``reflectances`` is the parallel list of forward-modeled
    band-reflectance dicts.

    A KD-tree over ``reflectances`` is built lazily on first inversion
    and cached on the instance — ``generate_lut()`` builds it eagerly so
    callers can pre-warm the structure off the request hot-path.
    """

    parameters: list[dict[str, float]]
    reflectances: list[dict[str, float]]
    bands: tuple[str, ...]
    geometry: ProsailGeometry
    _kd_tree: KDTree | None = field(default=None, repr=False, compare=False)

    def __len__(self) -> int:
        return len(self.parameters)

    def kd_tree(self) -> KDTree:
        """Return (and lazily build) the KD-tree over ``reflectances``.

        The tree is keyed on the band ordering in ``self.bands`` so the
        same axis convention is enforced for every retrieval against
        this LUT.
        """

        if self._kd_tree is None:
            self._kd_tree = KDTree([self._reflectance_vector(r) for r in self.reflectances])
        return self._kd_tree

    def _reflectance_vector(self, ref: dict[str, float]) -> tuple[float, ...]:
        # Missing bands fall back to 0.0; the brute-force baseline
        # silently skipped them, which would also bias the KD-tree
        # search. Forcing a stable per-band vector keeps both backends
        # comparable.
        return tuple(float(ref.get(band, 0.0)) for band in self.bands)


# ---------------------------------------------------------------------------
# LUT generation
# ---------------------------------------------------------------------------


_PARAMETER_AXES: dict[str, tuple[str, str]] = {
    # parameter name -> (target_object, attribute_name)
    "LAI": ("canopy", "lai"),
    "Cab": ("leaf", "chlorophyll_ug_cm2"),
    "Car": ("leaf", "carotenoid_ug_cm2"),
    "Cw": ("leaf", "water_cm"),
    "Cm": ("leaf", "dry_matter_g_cm2"),
    "N": ("leaf", "n_layers"),
    "leaf_angle_deg": ("canopy", "leaf_angle_deg"),
    "soil_reflectance": ("canopy", "soil_reflectance"),
}


def _linspace(low: float, high: float, count: int) -> list[float]:
    if count <= 1:
        return [low]
    step = (high - low) / (count - 1)
    return [low + i * step for i in range(count)]


def _grid(parameter_ranges: dict[str, tuple[float, float]], density: int) -> list[dict[str, float]]:
    """Cartesian product of ``parameter_ranges`` at ``density`` levels per axis."""

    keys = list(parameter_ranges.keys())
    axes = [_linspace(low, high, density) for low, high in parameter_ranges.values()]

    grid: list[dict[str, float]] = [{}]
    for key, axis in zip(keys, axes, strict=True):
        next_grid: list[dict[str, float]] = []
        for partial in grid:
            for value in axis:
                next_grid.append({**partial, key: value})
        grid = next_grid
    return grid


def _forward(params: dict[str, float], geometry: ProsailGeometry) -> dict[str, float]:
    leaf = LeafOpticalProperties()
    canopy = CanopyParameters(
        sun_zenith_deg=geometry.sun_zenith_deg,
        view_zenith_deg=geometry.view_zenith_deg,
    )
    for key, value in params.items():
        if key not in _PARAMETER_AXES:
            raise ValueError(f"unsupported PROSAIL parameter: {key}")
        target, attr = _PARAMETER_AXES[key]
        setattr(leaf if target == "leaf" else canopy, attr, value)
    leaf_ref = prospect_reflectance(leaf)
    return sail_canopy_reflectance(leaf_ref, canopy)


def generate_lut(
    parameter_ranges: dict[str, tuple[float, float]],
    density: int = 8,
    *,
    geometry: ProsailGeometry | None = None,
    bands: tuple[str, ...] = _DEFAULT_BANDS,
    build_index: bool = True,
) -> ProsailLUT:
    """Generate a PROSAIL LUT covering ``parameter_ranges``.

    ``density`` is the number of samples **per axis**, so the total LUT
    size is ``density ** len(parameter_ranges)``. The default of ``8``
    keeps a 5-axis LUT under 33 k entries.

    When ``build_index=True`` (the default) the KD-tree is built
    eagerly — this keeps the per-request hot-path of
    :func:`invert` index-build-free, which matters for the synchronous
    ``digital-twin-engine`` endpoint.
    """

    if not parameter_ranges:
        raise ValueError("parameter_ranges must not be empty")
    if density < 2:
        raise ValueError("density must be >= 2")
    for key, (low, high) in parameter_ranges.items():
        if low >= high:
            raise ValueError(f"invalid range for {key!r}: low must be < high")
        if key not in _PARAMETER_AXES:
            raise ValueError(f"unsupported PROSAIL parameter: {key}")

    geom = geometry or ProsailGeometry(sun_zenith_deg=30.0, view_zenith_deg=0.0, relative_azimuth_deg=0.0)

    grid = _grid(parameter_ranges, density)
    reflectances = [_forward(p, geom) for p in grid]
    lut = ProsailLUT(
        parameters=grid,
        reflectances=reflectances,
        bands=bands,
        geometry=geom,
    )
    if build_index:
        lut.kd_tree()
    return lut


# ---------------------------------------------------------------------------
# Inversion
# ---------------------------------------------------------------------------


def _distance(a: dict[str, float], b: dict[str, float], bands: tuple[str, ...]) -> float:
    total = 0.0
    for band in bands:
        if band in a and band in b:
            total += (a[band] - b[band]) ** 2
    return math.sqrt(total)


def invert(
    reflectance: dict[str, float],
    geometry: ProsailGeometry,
    soil_prior: dict[str, float] | None = None,  # noqa: ARG001 - reserved for v3.2
    *,
    lut: ProsailLUT,
    top_k: int = _DEFAULT_TOP_K,
    backend: str = "kd_tree",
) -> ProsailRetrieval:
    """Retrieve canopy parameters from observed ``reflectance``.

    ``reflectance`` is keyed by band name (e.g. ``"red"``, ``"nir"``,
    ``"swir1"``). Uncertainty is the 1-sigma standard deviation across the
    ``top_k`` nearest LUT matches — this is the standard k-NN inverse
    uncertainty surrogate referenced in ADR-015.

    ``backend`` selects the retrieval strategy:

    * ``"kd_tree"`` (default) — log-time k-NN over the cached KD-tree.
    * ``"brute_force"`` — linear scan; kept for diagnostics and as the
      regression baseline that proves the KD-tree returns the same
      neighbours.
    """

    if len(lut) == 0:
        raise ValueError("LUT is empty — call generate_lut() first")
    if top_k < 1:
        raise ValueError("top_k must be >= 1")
    if backend not in {"kd_tree", "brute_force"}:
        raise ValueError(f"backend must be 'kd_tree' or 'brute_force', got {backend!r}")
    if (
        abs(lut.geometry.sun_zenith_deg - geometry.sun_zenith_deg) > 1e-6
        or abs(lut.geometry.view_zenith_deg - geometry.view_zenith_deg) > 1e-6
        or abs(lut.geometry.relative_azimuth_deg - geometry.relative_azimuth_deg) > 1e-6
    ):
        raise ValueError("geometry mismatch — regenerate the LUT for this scene")

    bands = lut.bands
    k = min(top_k, len(lut))

    if backend == "kd_tree":
        target = tuple(float(reflectance.get(band, 0.0)) for band in bands)
        neighbours = lut.kd_tree().query(target, k=k)
        top = [idx for _d, idx in neighbours]
        best_distance = neighbours[0][0]
        worst_distance = neighbours[-1][0]
    else:
        distances = [_distance(reflectance, ref, bands) for ref in lut.reflectances]
        indexed = sorted(range(len(lut)), key=lambda i: distances[i])
        top = indexed[:k]
        best_distance = distances[top[0]]
        worst_distance = distances[top[-1]]

    # Mean parameters across the k-NN.
    mean_params: dict[str, float] = {}
    keys = list(lut.parameters[0])
    for key in keys:
        mean_params[key] = sum(lut.parameters[i][key] for i in top) / k

    # Per-parameter 1-sigma across the k-NN.
    uncertainty: dict[str, float] = {}
    if k <= 1:
        uncertainty = dict.fromkeys(keys, 0.0)
    else:
        for key in keys:
            mu = mean_params[key]
            var = sum((lut.parameters[i][key] - mu) ** 2 for i in top) / (k - 1)
            uncertainty[key] = math.sqrt(var)

    diagnostics: dict[str, Any] = {
        "lut_size": len(lut),
        "top_k": k,
        "best_distance": best_distance,
        "worst_distance_in_top_k": worst_distance,
        "bands": list(bands),
        "backend": backend,
    }

    return ProsailRetrieval(
        parameters=mean_params,
        uncertainty=uncertainty,
        diagnostics=diagnostics,
    )
