"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getAllServiceUrls = exports.getServiceUrl = exports.SERVICE_PORT_ALIASES = exports.SERVICE_REGISTRY = exports.SERVICE_PORTS = void 0;
exports.SERVICE_PORTS = {
    FIELD_MANAGEMENT: 3000,
    USER_SERVICE: 3025,
    PARTNER_AUTH: 3030,
    MARKETPLACE: 3010,
    RESEARCH_CORE: 3015,
    DISASTER_ASSESSMENT: 3020,
    VEGETATION_ANALYSIS: 8090,
    INDICATORS: 8091,
    WEATHER: 8092,
    ADVISORY: 8093,
    IRRIGATION_SMART: 8094,
    CROP_INTELLIGENCE: 8095,
    NDVI_PROCESSOR: 8118,
    VIRTUAL_SENSORS: 8119,
    FIELD_INTELLIGENCE: 8120,
    SKILLS_SERVICE: 8121,
    LAI_ESTIMATION: 3022,
    CROP_GROWTH_MODEL: 3023,
    YIELD_PREDICTION: 8152,
    YIELD_ENGINE: 8098,
    YIELD_PREDICTION_LEGACY: 3021,
    TASK_SERVICE: 8103,
    EQUIPMENT: 8101,
    NOTIFICATIONS: 8110,
    ALERT_SERVICE: 8113,
    AUDIT_SERVICE: 8114,
    BILLING_CORE: 8089,
    PROVIDER_CONFIG: 8104,
    INVENTORY: 8116,
    WS_GATEWAY: 8081,
    CHAT_SERVICE: 8115,
    FIELD_CHAT: 8099,
    COMMUNITY_CHAT: 8097,
    IOT_SERVICE: 8117,
    IOT_GATEWAY: 8106,
    IOT_SENSOR_HUB: 8251,
    COPILOT_API: 8088,
    AI_ADVISOR: 8112,
    AI_AGENTS_CORE: 8161,
    AI_AGENTS_SERVICE: 8130,
    AI_CHAT_ASSISTANT: 8260,
    AGENT_REGISTRY: 8160,
    LLM_ORCHESTRATOR: 8164,
    KNOWLEDGE_GRAPH: 8140,
    CODE_FIX_AGENT: 8162,
    CODE_REVIEW_SERVICE: 8102,
    YOLO_VISION: 8150,
    GROUND_VISION: 8182,
    TERRAIN_CORE: 8185,
    HYDROLOGY: 8165,
    LEVELING_OPTIMIZER: 8170,
    EDGE_ORCHESTRATOR: 8180,
    VLLM_DEEPSEEK: 8270,
    SOIL_ANALYSIS: 8134,
    PEST_DETECTION: 8125,
    DRONE_SERVICE: 8126,
    COOPERATIVE: 8127,
    GLOBALGAP: 8128,
    TRACEABILITY: 8123,
    CRM_SERVICE: 8131,
    ASTRONOMICAL_CALENDAR: 8111,
    LOGISTICS: 8167,
    SUPPLY_CHAIN: 8230,
    LOWCODE_ENGINE: 8132,
    COMMUNITY: 8133,
    WECHAT: 8135,
    WHATSAPP_BOT: 8240,
    USSD_GATEWAY: 8183,
    FERTIGATION_ENGINE: 8252,
    IRRIGATION_CYCLE_ENGINE: 8250,
    DIGITAL_TWIN: 8253,
    MCP_SERVER: 8201,
    CARBON_SERVICE: 8195,
    ADMIN: 3001,
    WEB: 3002,
    KONG_GATEWAY: 8000,
    KONG_ADMIN: 8001,
    NATS: 4222,
    NATS_MONITOR: 8222,
    POSTGRES: 5432,
    PGBOUNCER: 6432,
    REDIS: 6379,
};
exports.SERVICE_REGISTRY = {
    'field-management': { key: 'FIELD_MANAGEMENT', port: exports.SERVICE_PORTS.FIELD_MANAGEMENT, name: 'Field Management', nameAr: 'إدارة الحقول', kongRoute: '/api/v1/fields', type: 'nodejs', layer: 'core' },
    'user-service': { key: 'USER_SERVICE', port: exports.SERVICE_PORTS.USER_SERVICE, name: 'User Service', nameAr: 'خدمة المستخدمين', kongRoute: '/api/v1/auth', type: 'nodejs', layer: 'core' },
    'weather-service': { key: 'WEATHER', port: exports.SERVICE_PORTS.WEATHER, name: 'Weather Service', nameAr: 'خدمة الطقس', kongRoute: '/api/v1/weather', type: 'python', layer: 'acquisition' },
    'vegetation-analysis': { key: 'VEGETATION_ANALYSIS', port: exports.SERVICE_PORTS.VEGETATION_ANALYSIS, name: 'Vegetation Analysis', nameAr: 'تحليل الغطاء النباتي', kongRoute: '/api/v1/satellite', type: 'python', layer: 'intelligence' },
    'crop-intelligence': { key: 'CROP_INTELLIGENCE', port: exports.SERVICE_PORTS.CROP_INTELLIGENCE, name: 'Crop Intelligence', nameAr: 'ذكاء المحاصيل', kongRoute: '/api/v1/crop-health', type: 'python', layer: 'intelligence' },
    'advisory-service': { key: 'ADVISORY', port: exports.SERVICE_PORTS.ADVISORY, name: 'Advisory Service', nameAr: 'خدمة الاستشارات', kongRoute: '/api/v1/advisory', type: 'python', layer: 'decision' },
    'irrigation-smart': { key: 'IRRIGATION_SMART', port: exports.SERVICE_PORTS.IRRIGATION_SMART, name: 'Smart Irrigation', nameAr: 'الري الذكي', kongRoute: '/api/v1/irrigation', type: 'python', layer: 'decision' },
    'task-service': { key: 'TASK_SERVICE', port: exports.SERVICE_PORTS.TASK_SERVICE, name: 'Task Service', nameAr: 'خدمة المهام', kongRoute: '/api/v1/tasks', type: 'python', layer: 'business' },
    'equipment-service': { key: 'EQUIPMENT', port: exports.SERVICE_PORTS.EQUIPMENT, name: 'Equipment Service', nameAr: 'خدمة المعدات', kongRoute: '/api/v1/equipment', type: 'python', layer: 'business' },
    'notification-service': { key: 'NOTIFICATIONS', port: exports.SERVICE_PORTS.NOTIFICATIONS, name: 'Notification Service', nameAr: 'خدمة الإشعارات', kongRoute: '/api/v1/notifications', type: 'python', layer: 'business' },
    'alert-service': { key: 'ALERT_SERVICE', port: exports.SERVICE_PORTS.ALERT_SERVICE, name: 'Alert Service', nameAr: 'خدمة التنبيهات', kongRoute: '/api/v1/alerts', type: 'python', layer: 'business' },
    'billing-core': { key: 'BILLING_CORE', port: exports.SERVICE_PORTS.BILLING_CORE, name: 'Billing Core', nameAr: 'الفوترة', kongRoute: '/api/v1/billing', type: 'python', layer: 'business' },
    'marketplace-service': { key: 'MARKETPLACE', port: exports.SERVICE_PORTS.MARKETPLACE, name: 'Marketplace', nameAr: 'السوق', kongRoute: '/api/v1/marketplace', type: 'nodejs', layer: 'business' },
    'chat-service': { key: 'CHAT_SERVICE', port: exports.SERVICE_PORTS.CHAT_SERVICE, name: 'Chat Service', nameAr: 'خدمة الدردشة', kongRoute: '/api/v1/chat', type: 'nodejs', layer: 'business' },
    'iot-service': { key: 'IOT_SERVICE', port: exports.SERVICE_PORTS.IOT_SERVICE, name: 'IoT Service', nameAr: 'خدمة إنترنت الأشياء', kongRoute: '/api/v1/iot', type: 'nodejs', layer: 'acquisition' },
    'copilot-api': { key: 'COPILOT_API', port: exports.SERVICE_PORTS.COPILOT_API, name: 'Copilot API', nameAr: 'المساعد الذكي', kongRoute: '/api/v1/copilot', type: 'python', layer: 'intelligence' },
    'yolo-vision': { key: 'YOLO_VISION', port: exports.SERVICE_PORTS.YOLO_VISION, name: 'YOLO Vision Service', nameAr: 'خدمة الرؤية الحاسوبية', kongRoute: '/api/v1/vision', type: 'python', layer: 'intelligence' },
    'terrain-core': { key: 'TERRAIN_CORE', port: exports.SERVICE_PORTS.TERRAIN_CORE, name: 'Terrain Core', nameAr: 'تحليل التضاريس', kongRoute: '/api/v1/terrain', type: 'python', layer: 'intelligence' },
    'crm-service': { key: 'CRM_SERVICE', port: exports.SERVICE_PORTS.CRM_SERVICE, name: 'CRM Service', nameAr: 'إدارة علاقات المزارعين', kongRoute: '/api/v1/crm', type: 'python', layer: 'business' },
    'community-chat': { key: 'COMMUNITY_CHAT', port: exports.SERVICE_PORTS.COMMUNITY_CHAT, name: 'Community Chat', nameAr: 'دردشة المجتمع', kongRoute: '/api/v1/community', type: 'nodejs', layer: 'business', deprecated: true, replacedBy: 'CHAT_SERVICE' },
    'vllm-deepseek': { key: 'VLLM_DEEPSEEK', port: exports.SERVICE_PORTS.VLLM_DEEPSEEK, name: 'vLLM DeepSeek Inference Server', nameAr: 'خادم استدلال vLLM ديب سيك', kongRoute: '/api/v1/vllm', type: 'python', layer: 'intelligence' },
    'indicators-service': { key: 'INDICATORS', port: exports.SERVICE_PORTS.INDICATORS, name: 'Indicators Service', nameAr: 'خدمة المؤشرات', kongRoute: '/api/v1/indicators', type: 'python', layer: 'intelligence' },
    'virtual-sensors': { key: 'VIRTUAL_SENSORS', port: exports.SERVICE_PORTS.VIRTUAL_SENSORS, name: 'Virtual Sensors', nameAr: 'المستشعرات الافتراضية', kongRoute: '/api/v1/virtual-sensors', type: 'python', layer: 'acquisition' },
    'field-intelligence': { key: 'FIELD_INTELLIGENCE', port: exports.SERVICE_PORTS.FIELD_INTELLIGENCE, name: 'Field Intelligence', nameAr: 'ذكاء الحقول', kongRoute: '/api/v1/field-intelligence', type: 'python', layer: 'intelligence' },
    'skills-service': { key: 'SKILLS_SERVICE', port: exports.SERVICE_PORTS.SKILLS_SERVICE, name: 'Skills Service', nameAr: 'خدمة المهارات', kongRoute: '/api/v1/skills', type: 'python', layer: 'intelligence' },
    'lai-estimation': { key: 'LAI_ESTIMATION', port: exports.SERVICE_PORTS.LAI_ESTIMATION, name: 'LAI Estimation', nameAr: 'تقدير LAI', kongRoute: '/api/v1/lai', type: 'nodejs', layer: 'intelligence' },
    'ndvi-processor': { key: 'NDVI_PROCESSOR', port: exports.SERVICE_PORTS.NDVI_PROCESSOR, name: 'NDVI Processor', nameAr: 'معالج NDVI', kongRoute: '/api/v1/ndvi', type: 'python', layer: 'intelligence', deprecated: true, replacedBy: 'VEGETATION_ANALYSIS' },
    'disaster-assessment': { key: 'DISASTER_ASSESSMENT', port: exports.SERVICE_PORTS.DISASTER_ASSESSMENT, name: 'Disaster Assessment', nameAr: 'تقييم الكوارث', kongRoute: '/api/v1/disaster', type: 'nodejs', layer: 'intelligence' },
    'soil-analysis-service': { key: 'SOIL_ANALYSIS', port: exports.SERVICE_PORTS.SOIL_ANALYSIS, name: 'Soil Analysis Service', nameAr: 'خدمة تحليل التربة', kongRoute: '/api/v1/soil', type: 'python', layer: 'intelligence' },
    'pest-detection-service': { key: 'PEST_DETECTION', port: exports.SERVICE_PORTS.PEST_DETECTION, name: 'Pest Detection Service', nameAr: 'خدمة كشف الآفات', kongRoute: '/api/v1/pest-detection', type: 'python', layer: 'intelligence' },
    'knowledge-graph': { key: 'KNOWLEDGE_GRAPH', port: exports.SERVICE_PORTS.KNOWLEDGE_GRAPH, name: 'Knowledge Graph', nameAr: 'الرسم البياني المعرفي', kongRoute: '/api/v1/knowledge', type: 'python', layer: 'intelligence' },
    'digital-twin-engine': { key: 'DIGITAL_TWIN', port: exports.SERVICE_PORTS.DIGITAL_TWIN, name: 'Digital Twin Engine', nameAr: 'محرك التوأم الرقمي', kongRoute: '/api/v1/digital-twin', type: 'python', layer: 'intelligence' },
    'hydrology-service': { key: 'HYDROLOGY', port: exports.SERVICE_PORTS.HYDROLOGY, name: 'Hydrology Service', nameAr: 'خدمة الهيدرولوجيا', kongRoute: '/api/v1/hydrology', type: 'python', layer: 'intelligence' },
    'ai-agents-core': { key: 'AI_AGENTS_CORE', port: exports.SERVICE_PORTS.AI_AGENTS_CORE, name: 'AI Agents Core', nameAr: 'نواة الوكلاء الذكية', kongRoute: '/api/v1/ai-agents', type: 'python', layer: 'intelligence' },
    'ai-agents-service': { key: 'AI_AGENTS_SERVICE', port: exports.SERVICE_PORTS.AI_AGENTS_SERVICE, name: 'AI Agents Service', nameAr: 'خدمة الوكلاء الذكية', kongRoute: '/api/v1/ai-agents-service', type: 'python', layer: 'intelligence' },
    'code-fix-agent': { key: 'CODE_FIX_AGENT', port: exports.SERVICE_PORTS.CODE_FIX_AGENT, name: 'Code Fix Agent', nameAr: 'وكيل إصلاح الكود', kongRoute: '/api/v1/code-fix', type: 'python', layer: 'intelligence' },
    'astronomical-calendar': { key: 'ASTRONOMICAL_CALENDAR', port: exports.SERVICE_PORTS.ASTRONOMICAL_CALENDAR, name: 'Astronomical Calendar', nameAr: 'التقويم الفلكي', kongRoute: '/api/v1/astronomy', type: 'python', layer: 'acquisition' },
    'iot-gateway': { key: 'IOT_GATEWAY', port: exports.SERVICE_PORTS.IOT_GATEWAY, name: 'IoT Gateway', nameAr: 'بوابة إنترنت الأشياء', kongRoute: '/api/v1/iot-gateway', type: 'python', layer: 'acquisition' },
    'iot-sensor-hub': { key: 'IOT_SENSOR_HUB', port: exports.SERVICE_PORTS.IOT_SENSOR_HUB, name: 'IoT Sensor Hub', nameAr: 'مركز أجهزة الاستشعار', kongRoute: '/api/v1/iot/sensors', type: 'python', layer: 'acquisition' },
    'ground-vision-service': { key: 'GROUND_VISION', port: exports.SERVICE_PORTS.GROUND_VISION, name: 'Ground Vision Service', nameAr: 'خدمة الرؤية الأرضية', kongRoute: '/api/v1/ground-vision', type: 'python', layer: 'acquisition' },
    'edge-orchestrator-service': { key: 'EDGE_ORCHESTRATOR', port: exports.SERVICE_PORTS.EDGE_ORCHESTRATOR, name: 'Edge Orchestrator Service', nameAr: 'خدمة تنسيق الأجهزة الطرفية', kongRoute: '/api/v1/edge', type: 'python', layer: 'acquisition' },
    'crop-growth-model': { key: 'CROP_GROWTH_MODEL', port: exports.SERVICE_PORTS.CROP_GROWTH_MODEL, name: 'Crop Growth Model', nameAr: 'نموذج نمو المحاصيل', kongRoute: '/api/v1/crop-growth', type: 'nodejs', layer: 'decision' },
    'yield-prediction-service': { key: 'YIELD_PREDICTION', port: exports.SERVICE_PORTS.YIELD_PREDICTION, name: 'Yield Prediction Service', nameAr: 'خدمة تنبؤ الإنتاجية', kongRoute: '/api/v1/yield', type: 'nodejs', layer: 'decision' },
    'yield-prediction': { key: 'YIELD_PREDICTION_LEGACY', port: exports.SERVICE_PORTS.YIELD_PREDICTION_LEGACY, name: 'Yield Prediction (Legacy)', nameAr: 'تنبؤ الغلة (القديمة)', kongRoute: '/yield-legacy', type: 'nodejs', layer: 'decision', deprecated: true, replacedBy: 'YIELD_PREDICTION' },
    'ai-advisor': { key: 'AI_ADVISOR', port: exports.SERVICE_PORTS.AI_ADVISOR, name: 'AI Advisor', nameAr: 'المستشار الذكي', kongRoute: '/api/v1/ai-advisor', type: 'python', layer: 'decision' },
    'leveling-optimizer-service': { key: 'LEVELING_OPTIMIZER', port: exports.SERVICE_PORTS.LEVELING_OPTIMIZER, name: 'Leveling Optimizer Service', nameAr: 'خدمة تحسين التسوية', kongRoute: '/api/v1/leveling', type: 'python', layer: 'decision' },
    'drone-service': { key: 'DRONE_SERVICE', port: exports.SERVICE_PORTS.DRONE_SERVICE, name: 'Drone Service', nameAr: 'خدمة الطائرات المسيرة', kongRoute: '/api/v1/drones', type: 'python', layer: 'decision' },
    'llm-orchestrator-service': { key: 'LLM_ORCHESTRATOR', port: exports.SERVICE_PORTS.LLM_ORCHESTRATOR, name: 'LLM Orchestrator Service', nameAr: 'خدمة تنسيق الذكاء الاصطناعي', kongRoute: '/api/v1/llm', type: 'python', layer: 'decision' },
    'fertigation-engine': { key: 'FERTIGATION_ENGINE', port: exports.SERVICE_PORTS.FERTIGATION_ENGINE, name: 'Fertigation Engine', nameAr: 'محرك التسميد بالري', kongRoute: '/api/v1/fertigation', type: 'python', layer: 'decision' },
    'irrigation-cycle-engine': { key: 'IRRIGATION_CYCLE_ENGINE', port: exports.SERVICE_PORTS.IRRIGATION_CYCLE_ENGINE, name: 'Irrigation Cycle Engine', nameAr: 'محرك دورات الري', kongRoute: '/api/v1/irrigation/cycles', type: 'python', layer: 'decision' },
    'ws-gateway': { key: 'WS_GATEWAY', port: exports.SERVICE_PORTS.WS_GATEWAY, name: 'WebSocket Gateway', nameAr: 'بوابة WebSocket', kongRoute: '/ws', type: 'python', layer: 'business' },
    'research-core': { key: 'RESEARCH_CORE', port: exports.SERVICE_PORTS.RESEARCH_CORE, name: 'Research Core', nameAr: 'نواة البحث العلمي', kongRoute: '/api/v1/research', type: 'nodejs', layer: 'business' },
    'mcp-server': { key: 'MCP_SERVER', port: exports.SERVICE_PORTS.MCP_SERVER, name: 'MCP Server', nameAr: 'خادم MCP', kongRoute: '/api/v1/mcp', type: 'python', layer: 'business' },
    'audit-service': { key: 'AUDIT_SERVICE', port: exports.SERVICE_PORTS.AUDIT_SERVICE, name: 'Audit Service', nameAr: 'خدمة التدقيق', kongRoute: '/api/v1/audit', type: 'python', layer: 'business' },
    'lowcode-engine': { key: 'LOWCODE_ENGINE', port: exports.SERVICE_PORTS.LOWCODE_ENGINE, name: 'Low-Code Engine', nameAr: 'محرك التطوير منخفض الكود', kongRoute: '/api/v1/lowcode', type: 'python', layer: 'business' },
    'community-service': { key: 'COMMUNITY', port: exports.SERVICE_PORTS.COMMUNITY, name: 'Community Service', nameAr: 'خدمة المجتمع الزراعي', kongRoute: '/api/v1/community', type: 'python', layer: 'business' },
    'wechat-service': { key: 'WECHAT', port: exports.SERVICE_PORTS.WECHAT, name: 'WeChat Service (Deprecated)', nameAr: 'خدمة ويتشات (مُهملة)', kongRoute: '/api/v1/wechat', type: 'python', layer: 'business' },
    'agent-registry': { key: 'AGENT_REGISTRY', port: exports.SERVICE_PORTS.AGENT_REGISTRY, name: 'Agent Registry', nameAr: 'سجل الوكلاء', kongRoute: '/api/v1/agents', type: 'python', layer: 'business' },
    'code-review-service': { key: 'CODE_REVIEW_SERVICE', port: exports.SERVICE_PORTS.CODE_REVIEW_SERVICE, name: 'Code Review Service', nameAr: 'خدمة مراجعة الكود', kongRoute: '/api/v1/code-review', type: 'python', layer: 'business' },
    'globalgap-compliance': { key: 'GLOBALGAP', port: exports.SERVICE_PORTS.GLOBALGAP, name: 'GlobalGAP Compliance', nameAr: 'التوافق مع GlobalGAP', kongRoute: '/api/v1/globalgap', type: 'python', layer: 'business' },
    'logistics-service': { key: 'LOGISTICS', port: exports.SERVICE_PORTS.LOGISTICS, name: 'Logistics Service', nameAr: 'خدمة اللوجستيات', kongRoute: '/api/v1/logistics', type: 'python', layer: 'business' },
    'cooperative-service': { key: 'COOPERATIVE', port: exports.SERVICE_PORTS.COOPERATIVE, name: 'Cooperative Service', nameAr: 'خدمة التعاونيات', kongRoute: '/api/v1/cooperatives', type: 'python', layer: 'business' },
    'traceability-service': { key: 'TRACEABILITY', port: exports.SERVICE_PORTS.TRACEABILITY, name: 'Traceability Service', nameAr: 'خدمة التتبع', kongRoute: '/api/v1/traceability', type: 'python', layer: 'business' },
    'supply-chain-service': { key: 'SUPPLY_CHAIN', port: exports.SERVICE_PORTS.SUPPLY_CHAIN, name: 'Supply Chain Service', nameAr: 'خدمة سلسلة التوريد', kongRoute: '/api/v1/supply-chain', type: 'python', layer: 'business' },
    'whatsapp-bot-service': { key: 'WHATSAPP_BOT', port: exports.SERVICE_PORTS.WHATSAPP_BOT, name: 'WhatsApp Bot Service', nameAr: 'خدمة بوت واتساب', kongRoute: '/api/v1/whatsapp', type: 'python', layer: 'business' },
    'ai-chat-assistant': { key: 'AI_CHAT_ASSISTANT', port: exports.SERVICE_PORTS.AI_CHAT_ASSISTANT, name: 'AI Chat Assistant', nameAr: 'مساعد الدردشة الذكي', kongRoute: '/api/v1/ai-chat', type: 'python', layer: 'business' },
    'ussd-gateway': { key: 'USSD_GATEWAY', port: exports.SERVICE_PORTS.USSD_GATEWAY, name: 'USSD Gateway', nameAr: 'بوابة USSD', kongRoute: '/api/v1/ussd', type: 'python', layer: 'business' },
    'inventory-service': { key: 'INVENTORY', port: exports.SERVICE_PORTS.INVENTORY, name: 'Inventory Service', nameAr: 'خدمة المخزون', kongRoute: '/api/v1/inventory', type: 'python', layer: 'business' },
    'provider-config': { key: 'PROVIDER_CONFIG', port: exports.SERVICE_PORTS.PROVIDER_CONFIG, name: 'Provider Config', nameAr: 'تكوين المزودين', kongRoute: '/api/v1/provider-config', type: 'python', layer: 'business' },
};
exports.SERVICE_PORT_ALIASES = {
    auth: exports.SERVICE_PORTS.USER_SERVICE,
    fieldCore: exports.SERVICE_PORTS.FIELD_MANAGEMENT,
    satellite: exports.SERVICE_PORTS.VEGETATION_ANALYSIS,
    indicators: exports.SERVICE_PORTS.INDICATORS,
    weather: exports.SERVICE_PORTS.WEATHER,
    weatherCore: exports.SERVICE_PORTS.WEATHER,
    fertilizer: exports.SERVICE_PORTS.ADVISORY,
    irrigation: exports.SERVICE_PORTS.IRRIGATION_SMART,
    cropHealth: exports.SERVICE_PORTS.CROP_INTELLIGENCE,
    virtualSensors: exports.SERVICE_PORTS.VIRTUAL_SENSORS,
    communityChat: exports.SERVICE_PORTS.COMMUNITY_CHAT,
    community: exports.SERVICE_PORTS.COMMUNITY_CHAT,
    yieldEngine: exports.SERVICE_PORTS.YIELD_ENGINE,
    equipment: exports.SERVICE_PORTS.EQUIPMENT,
    task: exports.SERVICE_PORTS.TASK_SERVICE,
    providerConfig: exports.SERVICE_PORTS.PROVIDER_CONFIG,
    notifications: exports.SERVICE_PORTS.NOTIFICATIONS,
    wsGateway: exports.SERVICE_PORTS.WS_GATEWAY,
    marketplace: exports.SERVICE_PORTS.MARKETPLACE,
    soilAnalysis: exports.SERVICE_PORTS.SOIL_ANALYSIS,
    drone: exports.SERVICE_PORTS.DRONE_SERVICE,
    cooperative: exports.SERVICE_PORTS.COOPERATIVE,
    traceability: exports.SERVICE_PORTS.TRACEABILITY,
    billing: exports.SERVICE_PORTS.BILLING_CORE,
    alerts: exports.SERVICE_PORTS.ALERT_SERVICE,
    inventory: exports.SERVICE_PORTS.INVENTORY,
    copilot: exports.SERVICE_PORTS.COPILOT_API,
    aiAdvisor: exports.SERVICE_PORTS.AI_ADVISOR,
    aiAgents: exports.SERVICE_PORTS.AI_AGENTS_CORE,
    knowledgeGraph: exports.SERVICE_PORTS.KNOWLEDGE_GRAPH,
    yoloVision: exports.SERVICE_PORTS.YOLO_VISION,
    terrainCore: exports.SERVICE_PORTS.TERRAIN_CORE,
    hydrology: exports.SERVICE_PORTS.HYDROLOGY,
    levelingOptimizer: exports.SERVICE_PORTS.LEVELING_OPTIMIZER,
    edgeOrchestrator: exports.SERVICE_PORTS.EDGE_ORCHESTRATOR,
    vllmDeepseek: exports.SERVICE_PORTS.VLLM_DEEPSEEK,
    advisory: exports.SERVICE_PORTS.ADVISORY,
    yieldPrediction: exports.SERVICE_PORTS.YIELD_PREDICTION,
    fieldIntelligence: exports.SERVICE_PORTS.FIELD_INTELLIGENCE,
    astronomicalCalendar: exports.SERVICE_PORTS.ASTRONOMICAL_CALENDAR,
    cropIntelligence: exports.SERVICE_PORTS.CROP_INTELLIGENCE,
    audit: exports.SERVICE_PORTS.AUDIT_SERVICE,
};
function getServiceUrl(port, host = 'localhost', protocol = 'http') {
    return `${protocol}://${host}:${port}`;
}
exports.getServiceUrl = getServiceUrl;
function getAllServiceUrls(host = 'localhost', protocol = 'http') {
    const urls = {};
    for (const [key, port] of Object.entries(exports.SERVICE_PORTS)) {
        urls[key] = `${protocol}://${host}:${port}`;
    }
    return urls;
}
exports.getAllServiceUrls = getAllServiceUrls;
//# sourceMappingURL=service-ports.js.map
