/**
 * Tasks Page - Mock Data (Development Fallback)
 * بيانات وهمية ثابتة للتطوير - صفحة المهام
 *
 * This file is separated from the page component to allow tree-shaking
 * in production builds. Mock data is only loaded as a fallback when the
 * API is unavailable during development.
 */

import type { Task } from '@/types';

export const MOCK_TASKS: Task[] = [
  {
    id: 'task-1',
    tenant_id: 'default',
    field_id: 'field-1',
    title: 'Soil Testing',
    title_ar: 'فحص التربة',
    description: 'Conduct soil testing for wheat field',
    description_ar: 'إجراء فحص التربة لحقل القمح',
    status: 'pending',
    priority: 'high',
    type: 'soil_testing',
    due_date: '2026-02-20T00:00:00Z',
    assigned_to: 'أحمد محمد',
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-01-15T08:00:00Z',
  },
  {
    id: 'task-2',
    tenant_id: 'default',
    field_id: 'field-2',
    title: 'Irrigation Repair',
    title_ar: 'إصلاح نظام الري',
    description: 'Fix drip irrigation system in sector B',
    description_ar: 'إصلاح نظام الري بالتنقيط في القطاع ب',
    status: 'in_progress',
    priority: 'urgent',
    type: 'maintenance',
    due_date: '2026-02-16T00:00:00Z',
    assigned_to: 'خالد عبدالله',
    created_at: '2026-01-10T10:30:00Z',
    updated_at: '2026-02-01T14:00:00Z',
  },
  {
    id: 'task-3',
    tenant_id: 'default',
    field_id: 'field-3',
    title: 'Fertilizer Application',
    title_ar: 'تطبيق السماد',
    description: 'Apply nitrogen fertilizer to barley field',
    description_ar: 'تطبيق سماد النيتروجين على حقل الشعير',
    status: 'completed',
    priority: 'medium',
    type: 'fertilizer',
    due_date: '2026-02-10T00:00:00Z',
    assigned_to: 'سعيد حسن',
    created_at: '2026-01-05T09:00:00Z',
    updated_at: '2026-02-10T16:00:00Z',
  },
  {
    id: 'task-4',
    tenant_id: 'default',
    field_id: 'field-4',
    title: 'Pest Scouting',
    title_ar: 'مسح الآفات',
    description: 'Scout for aphids in date palm grove',
    description_ar: 'مسح وجود المن في بستان النخيل',
    status: 'pending',
    priority: 'high',
    type: 'pest_control',
    due_date: '2026-02-18T00:00:00Z',
    assigned_to: 'محمد علي',
    created_at: '2026-01-20T07:30:00Z',
    updated_at: '2026-01-20T07:30:00Z',
  },
  {
    id: 'task-5',
    tenant_id: 'default',
    field_id: 'field-5',
    title: 'Harvest Preparation',
    title_ar: 'تجهيز الحصاد',
    description: 'Prepare equipment for wheat harvest',
    description_ar: 'تجهيز المعدات لحصاد القمح',
    status: 'pending',
    priority: 'medium',
    type: 'harvest',
    due_date: '2026-03-01T00:00:00Z',
    assigned_to: 'علي يوسف',
    created_at: '2026-02-01T11:00:00Z',
    updated_at: '2026-02-01T11:00:00Z',
  },
  {
    id: 'task-6',
    tenant_id: 'default',
    field_id: 'field-6',
    title: 'Water Quality Check',
    title_ar: 'فحص جودة المياه',
    description: 'Test irrigation water quality parameters',
    description_ar: 'فحص معايير جودة مياه الري',
    status: 'in_progress',
    priority: 'medium',
    type: 'water_management',
    due_date: '2026-02-17T00:00:00Z',
    assigned_to: 'فهد سالم',
    created_at: '2026-01-25T13:00:00Z',
    updated_at: '2026-02-05T09:00:00Z',
  },
  {
    id: 'task-7',
    tenant_id: 'default',
    field_id: 'field-7',
    title: 'Weed Control',
    title_ar: 'مكافحة الأعشاب',
    description: 'Apply herbicide to sorghum field borders',
    description_ar: 'تطبيق مبيد الأعشاب على حدود حقل الذرة الرفيعة',
    status: 'completed',
    priority: 'low',
    type: 'weed_control',
    due_date: '2026-02-05T00:00:00Z',
    assigned_to: 'أحمد محمد',
    created_at: '2026-01-08T08:30:00Z',
    updated_at: '2026-02-05T15:00:00Z',
  },
  {
    id: 'task-8',
    tenant_id: 'default',
    field_id: 'field-8',
    title: 'NDVI Analysis Review',
    title_ar: 'مراجعة تحليل NDVI',
    description: 'Review satellite NDVI data for all active fields',
    description_ar: 'مراجعة بيانات NDVI من الأقمار الصناعية لجميع الحقول النشطة',
    status: 'in_progress',
    priority: 'low',
    type: 'analysis',
    due_date: '2026-02-22T00:00:00Z',
    assigned_to: 'سعيد حسن',
    created_at: '2026-02-01T10:00:00Z',
    updated_at: '2026-02-10T11:00:00Z',
  },
  {
    id: 'task-9',
    tenant_id: 'default',
    field_id: 'field-9',
    title: 'Equipment Maintenance',
    title_ar: 'صيانة المعدات',
    description: 'Schedule tractor maintenance before planting season',
    description_ar: 'جدولة صيانة الجرار قبل موسم الزراعة',
    status: 'pending',
    priority: 'high',
    type: 'maintenance',
    due_date: '2026-02-25T00:00:00Z',
    assigned_to: 'خالد عبدالله',
    created_at: '2026-02-05T14:00:00Z',
    updated_at: '2026-02-05T14:00:00Z',
  },
  {
    id: 'task-10',
    tenant_id: 'default',
    field_id: 'field-10',
    title: 'Crop Rotation Planning',
    title_ar: 'تخطيط الدورة الزراعية',
    description: 'Plan next season crop rotation for fields 1-5',
    description_ar: 'تخطيط الدورة الزراعية للموسم القادم للحقول ١-٥',
    status: 'completed',
    priority: 'medium',
    type: 'planning',
    due_date: '2026-02-08T00:00:00Z',
    assigned_to: 'محمد علي',
    created_at: '2026-01-12T09:00:00Z',
    updated_at: '2026-02-08T17:00:00Z',
  },
  {
    id: 'task-11',
    tenant_id: 'default',
    field_id: 'field-1',
    title: 'Seed Procurement',
    title_ar: 'شراء البذور',
    description: 'Order certified wheat seeds for next season',
    description_ar: 'طلب بذور قمح معتمدة للموسم القادم',
    status: 'pending',
    priority: 'urgent',
    type: 'procurement',
    due_date: '2026-02-19T00:00:00Z',
    assigned_to: 'علي يوسف',
    created_at: '2026-02-08T08:00:00Z',
    updated_at: '2026-02-08T08:00:00Z',
  },
  {
    id: 'task-12',
    tenant_id: 'default',
    field_id: 'field-3',
    title: 'Sensor Installation',
    title_ar: 'تركيب المستشعرات',
    description: 'Install soil moisture sensors in barley field',
    description_ar: 'تركيب مستشعرات رطوبة التربة في حقل الشعير',
    status: 'in_progress',
    priority: 'medium',
    type: 'iot',
    due_date: '2026-02-21T00:00:00Z',
    assigned_to: 'فهد سالم',
    created_at: '2026-02-03T10:30:00Z',
    updated_at: '2026-02-12T09:00:00Z',
  },
];
