apiVersion: v2
name: billing-core
description: SAHOOL Billing Core - Microservice
type: application
version: 1.0.0
appVersion: "16.0.0"
keywords:
  - sahool
  - billing
  - microservice
maintainers:
  - name: KAFAAT
    email: platform@kafaat.sa
