/**
 * Compliance Feature - Mock Data (Development Fallback)
 * بيانات وهمية للامتثال والجودة
 *
 * Separated from the API layer to reduce client bundle size.
 * This data is used as fallback when the API is unavailable.
 */

import type { ComplianceItem, Certification, ComplianceStats } from './types';

export const MOCK_COMPLIANCE: ComplianceItem[] = [
  {
    id: '1',
    category: 'Food Safety',
    categoryAr: 'سلامة الغذاء',
    requirement: 'Pesticide Residue Limits',
    requirementAr: 'حدود بقايا المبيدات',
    status: 'compliant',
    score: 95,
    maxScore: 100,
    lastAudit: '2026-01-15',
    nextAudit: '2026-04-15',
    metadata: {},
    createdAt: '2025-01-01T10:00:00Z',
    updatedAt: '2026-01-15T14:30:00Z',
  },
  {
    id: '2',
    category: 'Worker Safety',
    categoryAr: 'سلامة العمال',
    requirement: 'PPE Requirements',
    requirementAr: 'متطلبات معدات الحماية',
    status: 'compliant',
    score: 100,
    maxScore: 100,
    lastAudit: '2026-01-10',
    nextAudit: '2026-04-10',
    metadata: {},
    createdAt: '2025-01-01T10:00:00Z',
    updatedAt: '2026-01-10T11:00:00Z',
  },
  {
    id: '3',
    category: 'Environment',
    categoryAr: 'البيئة',
    requirement: 'Water Usage Records',
    requirementAr: 'سجلات استخدام المياه',
    status: 'partial',
    score: 75,
    maxScore: 100,
    lastAudit: '2026-01-12',
    nextAudit: '2026-04-12',
    notes: 'Missing irrigation logs for December',
    notesAr: 'سجلات الري مفقودة لشهر ديسمبر',
    metadata: {},
    createdAt: '2025-01-01T10:00:00Z',
    updatedAt: '2026-01-12T16:00:00Z',
  },
  {
    id: '4',
    category: 'Traceability',
    categoryAr: 'التتبع',
    requirement: 'Batch Identification',
    requirementAr: 'تعريف الدفعات',
    status: 'compliant',
    score: 92,
    maxScore: 100,
    lastAudit: '2026-01-08',
    nextAudit: '2026-04-08',
    metadata: {},
    createdAt: '2025-01-01T10:00:00Z',
    updatedAt: '2026-01-08T09:00:00Z',
  },
  {
    id: '5',
    category: 'Documentation',
    categoryAr: 'التوثيق',
    requirement: 'Training Records',
    requirementAr: 'سجلات التدريب',
    status: 'pending_review',
    score: 85,
    maxScore: 100,
    lastAudit: '2026-01-20',
    nextAudit: '2026-04-20',
    metadata: {},
    createdAt: '2025-01-01T10:00:00Z',
    updatedAt: '2026-01-20T10:00:00Z',
  },
];

export const MOCK_CERTIFICATIONS: Certification[] = [
  {
    id: '1',
    name: 'GlobalGAP',
    nameAr: 'جلوبال جاب',
    type: 'globalgap',
    issuer: 'GLOBALG.A.P.',
    issuerAr: 'منظمة جلوبال جاب',
    status: 'active',
    certificateNumber: 'GGN-12345-6789',
    issueDate: '2025-06-01',
    expiryDate: '2026-06-01',
    metadata: {},
  },
  {
    id: '2',
    name: 'Organic Certification',
    nameAr: 'شهادة العضوية',
    type: 'organic',
    issuer: 'Saudi Organic Authority',
    issuerAr: 'هيئة الزراعة العضوية',
    status: 'active',
    certificateNumber: 'ORG-SA-2025-001',
    issueDate: '2025-03-15',
    expiryDate: '2026-03-15',
    metadata: {},
  },
  {
    id: '3',
    name: 'ISO 22000',
    nameAr: 'آيزو 22000',
    type: 'iso',
    issuer: 'SGS',
    issuerAr: 'إس جي إس',
    status: 'pending',
    certificateNumber: '',
    issueDate: '',
    expiryDate: '',
    metadata: {},
  },
];

export const MOCK_STATS: ComplianceStats = {
  overallScore: 89,
  totalRequirements: 5,
  compliantCount: 3,
  partialCount: 1,
  nonCompliantCount: 0,
  pendingAudits: 1,
  activeCertifications: 2,
  expiringCertifications: 1,
  openFindings: 2,
  byCategory: {
    'Food Safety': { score: 95, total: 100 },
    'Worker Safety': { score: 100, total: 100 },
    Environment: { score: 75, total: 100 },
    Traceability: { score: 92, total: 100 },
    Documentation: { score: 85, total: 100 },
  },
};
