"""
SAHOOL Python Contracts (seed)
==============================

Python mirror of the TypeScript contracts in::

    packages/shared-types/src/contracts/

The TypeScript package is the canonical source of truth. The Python
counterparts here are hand-seeded and will be auto-generated by
``scripts/sync-contracts-to-python.ts`` (not yet implemented).

DO NOT edit by hand — regenerate via the sync script once it exists.
"""

from .service_ports import SERVICE_PORTS, ServicePorts

__all__ = ["SERVICE_PORTS", "ServicePorts"]
