apiVersion: v2
name: ws-gateway
description: SAHOOL Ws Gateway - Microservice
type: application
version: 1.0.0
appVersion: "16.0.0"
keywords:
  - sahool
  - ws
  - microservice
maintainers:
  - name: KAFAAT
    email: platform@kafaat.sa
