apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sahool-observability
  namespace: argocd
spec:
  project: sahool
  source:
    repoURL: REPLACE_WITH_YOUR_REPO_URL
    targetRevision: HEAD
    path: k8s/gitops-observability
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
